package:
  name: bodo
  version: {{ BODO_VERSION }}

source:
   path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  script_env:
  - CHECK_LICENSE_EXPIRED
  - CHECK_LICENSE_CORE_COUNT

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - setuptools
    - numba =0.57.1
    # Compatible with Numba requirements.
    # Resolves build issues on nightly
    - numpy >=1.23,<1.25
    - cython <3.0
    - pandas >=2,<2.2
    - fsspec >=2021.09
    - pyarrow =13.0.0
    - boost-cpp =1.82
    - hdf5 >=1.14,<1.15.0a0=*mpi_mpich_* # [not win]
    - h5py
    - mpich *=h* # [not win]
    - msmpi # [win]
    - mpi4py
    - vc # [win]
    - vs2015_runtime # [win]
    - vs2015_win-64 # [win]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas >=2,<2.2
    - fsspec >=2021.09
    - pyarrow =13.0.0
    - numba
    - openjdk >=9.0,<12
    - sqlalchemy
    - mpich *=h* # [not win]
    - msmpi # [win]
    - mpi4py
    - vs2015_runtime # [win]
    - vs2015_win-64 # [win]

  # run constrained will not install these packages when building,
  # but will restrict them if they are present in the conda env.
  # currently matplotlib is an optional dependency, and we only
  # support up to 3.5.1
  run_constrained:
    - matplotlib <= 3.5.1
  run_constrained:
    - numpy >=1.23,<1.25
  run_constrained:
    - scikit-learn =1.1.*
  run_constrained:
    - s3fs >=2022.1.0


test:
  imports:
    - bodo
  source_files:
    - examples/pi.py


about:
  home: https://bodo.ai
  license: Proprietary
  license_file: LICENSE.md
  summary: Python Supercomputing Analytics Platform
