# Copied from Iceberg Connector
parameters:
    name: ''
    pythonVersion: ''

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 240
  pool: ScalingVMSet

  steps:

  # Install Micromamba and Create Environment . Reference:
  # https://mamba.readthedocs.io/en/latest/installation.html#micromamba
  - script: |
      set -exo pipefail
      curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
      eval "$(./bin/micromamba shell hook -s posix)"
      micromamba create -y -n sas_build python=$PYTHON_VERSION maven credstash boa anaconda-client conda-verify -c conda-forge
    env:
      PYTHON_VERSION: ${{ parameters.pythonVersion }}
    displayName: 'Setup Conda Installation + Dependencies'

  - task: DownloadSecureFile@1
    name: secret_file
    displayName: 'Download Secrets File'
    inputs:
      secureFile: 'publish_binary_secrets'

  - script: |
      set -eo pipefail
      sudo chmod a+r $(secret_file.secureFilePath)
      sudo cp $(secret_file.secureFilePath) $HOME/secret_file

      artifactory_channel="bodo.ai"
      echo "artifactory_channel: $artifactory_channel"
      buildscripts/azurefs-sas-token-provider/publish_binary.sh $artifactory_channel
    env:
      BODO_CHANNEL_NAME: 'bodo.ai'
      TARGET_NAME: ${{ parameters.name }}
    displayName: 'Conda Build and Publish Bodo-AzureFS-SAS-Token-Provider Binary to Artifactory'
