---
- name: COMMON | wheel group nopasswd sudo
  lineinfile:
    path: /etc/sudoers
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  tags:
    - user

- name: COMMON | MPI Cluster user creation
  user:
    name: "{{ CLUSTER_USER }}"
    shell: /bin/bash
    home: "/home/{{ CLUSTER_USER }}"
    append: yes
    groups: wheel
  tags:
    - user

- name: COMMON | SSH Directory creation
  file:
    path: "/home/{{ CLUSTER_USER }}/.ssh"
    state: directory
    owner: "{{ CLUSTER_USER }}"
    group: "{{ CLUSTER_USER }}"
    mode: '0700'
  tags:
    - user

- name: COMMON | SSH Config upload
  copy:
    src: ssh_config
    dest: "/home/{{ CLUSTER_USER }}/.ssh/config"
    owner: "{{ CLUSTER_USER }}"
    group: "{{ CLUSTER_USER }}"
    mode: '0600'
  tags:
    - user
