self-hosted-runner:
  labels:
    - small
    - medium
    - large
    - xlarge
    - self-hosted-small
    - self-hosted-medium
    - self-hosted-large
    - self-hosted-xlarge
    - self-hosted-single-gpu
    - self-hosted-multi-gpu
