version: 2
updates:
  - package-ecosystem: "github-actions"
    # Auto-looks in `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      "github-actions":
        patterns:
          - "*"
