trigger:
- refs/tags/*

pr: none

schedules:
- cron: "0 5 * * *"
  displayName: 'Daily midnight build'
  branches:
    include:
    - master

stages:
- stage: Build_Bodo_Binary
  displayName: 'Build Bodo Binary'
  jobs:
  - job: find_suffix
    pool:
      vmImage: macOS-latest
    steps:
    - script: |
        export BUILD_DATE=`date  +"%Y-%m-%d"`
        export FILE_SUFFIX=built-${BUILD_DATE}
        echo "##vso[task.setvariable variable=fileSuffix;isOutput=true]$FILE_SUFFIX"
      displayName: 'write FILE_SUFFIX'
      name: suffix_step

  - template: buildscripts/azure/azure-build-binary-linux-macos.yml
    parameters:
      name: Linux
      vmImage: ubuntu-latest
  - template: buildscripts/azure/azure-build-binary-linux-macos.yml
    parameters:
      name: Mac
      vmImage: macOS-latest
  - template: buildscripts/azure/azure-build-binary-windows.yml
    parameters:
      name: Windows
      vmImage: vs2017-win2016

- stage: Test_Bodo_Binary
  displayName: Test Bodo Binary
  jobs:
  - template: buildscripts/azure/azure-test-binary-linux-macos.yml
    parameters:
      name: Mac
      vmImage: macOS-latest
      matrix:
        TEST_1P_SLOW:
          NP: 1
          PYTEST_MARKER: slow
        TEST_2P_SLOW:
          NP: 2
          PYTEST_MARKER: slow
        TEST_3P_SLOW:
          NP: 3
          PYTEST_MARKER: slow
        TEST_1P_NOT_SLOW:
          NP: 1
          PYTEST_MARKER: not slow
        TEST_2P_NOT SLOW:
          NP: 2
          PYTEST_MARKER: not slow
        TEST_3P_NOT_SLOW:
          NP: 3
          PYTEST_MARKER: not slow  
  - template: buildscripts/azure/azure-test-binary-linux-macos.yml
    parameters:
      name: Linux
      vmImage: ubuntu-latest
      matrix:
        TEST_1P_SLOW:
          NP: 1
          PYTEST_MARKER: slow
        TEST_2P_SLOW:
          NP: 2
          PYTEST_MARKER: slow
        TEST_3P_SLOW_FIRST_HALF:
          NP: 3
          PYTEST_MARKER: slow and firsthalf
        TEST_3P_SLOW_SECOND_HALF:
          NP: 3
          PYTEST_MARKER: slow and not firsthalf
        TEST_1P_NOT_SLOW:
          NP: 1
          PYTEST_MARKER: not slow
        TEST_2P_NOT SLOW:
          NP: 2
          PYTEST_MARKER: not slow
        TEST_3P_NOT_SLOW_FIRST_HALF:
          NP: 3
          PYTEST_MARKER: not slow and firsthalf
        TEST_3P_NOT_SLOW_SECOND_HALF:
          NP: 3
          PYTEST_MARKER: not slow and not firsthalf

