# Azure Pipeline that is triggered weekly or when a release is tagged.

trigger:
- refs/tags/*

pr: none

schedules:
- cron: "0 15 * * WED"
  displayName: 'Weekly np3 build'
  branches:
    include:
    - main

# NOTE: these variables determine artifactory channel to publish Bodo/BodoSQL/Iceberg packages.
# See get_channel.sh
# Originally added through Azure Pipeline UI.
variables:
  CHECK_LICENSE_EXPIRED: 1
  CHECK_LICENSE_CORE_COUNT: 1
  OBFUSCATE: 1

# Note: we only build the packages that we need for testing on the weekly pipeline (no PiP or ARM)
stages:
- stage: Build_Bodo_Binary
  displayName: 'Build Bodo Binary'
  jobs:
  - job: find_suffix
    pool:
      vmImage: macOS-latest
    steps:
    - script: |
        set -eo pipefail
        export BUILD_DATE=`date  +"%Y-%m-%d"`
        export FILE_SUFFIX=built-${BUILD_DATE}
        echo "##vso[task.setvariable variable=fileSuffix;isOutput=true]$FILE_SUFFIX"
      displayName: 'write FILE_SUFFIX'
      name: suffix_step

  # Bodo build:
  # Note: for all the bodo build steps,
  # the name string is used later in the buildscripts to determine which version of conda to install
  - template: buildscripts/bodo/azure/azure-build-conda-linux-macos.yml
    parameters:
      name: Linux
      buildMac: false
      pool:
        vmImage: ubuntu-latest
      platformBuild: false
      weeklyTest: true
  - template: buildscripts/bodo/azure/azure-build-conda-linux-macos.yml
    parameters:
      name: macOS
      buildMac: true
      pool:
        vmImage: macOS-latest
      platformBuild: false
      weeklyTest: true
#  - template: buildscripts/bodo/azure/azure-build-conda-windows.yml
#    parameters:
#      name: Windows
#      vmImage: windows-2019
#  - template: buildscripts/bodo/azure/azure-build-pip-windows.yml
#    parameters:
#      name: Windows_pip
#      vmImage: windows-2019

# Note: It is difficult to enforce the exact version of bodo to use for the build, outside of
# modifying the build recipe. Therefore, if we update BodoSQL's build process to require a specific version
# of Bodo, I'm requiring that we update the recipe in buildscripts/bodosql/conda-recipe/meta.yaml,
# and do a mini-release.

- stage: Build_BodoSQL_Binary
  displayName: 'Build BodoSQL Binary'
  dependsOn: Build_Bodo_Binary
  jobs:
  # BodoSQL build:
  - template: buildscripts/bodosql/azure/azure-build-conda.yml
    parameters:
      name: BodoSQL_Conda_Build
      CONDA_ENV: build_bodo_sql
      PYTHON_VERSION: 3.10
  # Uncomment when pip is enabled again.
  # # BodoSQL build:
  # - template: buildscripts/bodosql/azure/azure-build-pip.yml
  #   parameters:
  #     name: BodoSQL_Pip_Build

# NOTE: we don't do any builds here, as we assume the previous nightly run has built the needed
# packages and put them on conda

- stage: Test_Bodo_Binary
  displayName: Test Bodo Binary
  dependsOn: Build_Bodo_Binary
  jobs:

  # Bodo tests:

  - template: buildscripts/bodo/azure/azure-test-conda-linux-macos.yml
    parameters:
      name: macOS_38py
      ### NOTE: The template doesn't actually support this parameter!
      vmImage: macOS-latest
      useNumbaDev: false
      caching_test: false
      CONDA_ENV: 'bodo'
      PYTHON_VERSION: 3.8
      matrix:
        BODO_3P_1_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_1of10
        BODO_3P_2_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_2of10
        BODO_3P_3_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_3of10
        BODO_3P_4_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_4of10
        BODO_3P_5_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_5of10
        BODO_3P_6_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_6of10
        BODO_3P_7_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_7of10
        BODO_3P_8_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_8of10
        BODO_3P_9_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_9of10
        BODO_3P_10_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_10of10

  - template: buildscripts/bodo/azure/azure-test-conda-linux-macos.yml
    parameters:
      name: macOS_39py
      ### NOTE: The template doesn't actually support this parameter!
      vmImage: macOS-latest
      useNumbaDev: false
      caching_test: false
      CONDA_ENV: 'bodo'
      PYTHON_VERSION: 3.9
      matrix:
        BODO_3P_1_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_1of10
        BODO_3P_2_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_2of10
        BODO_3P_3_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_3of10
        BODO_3P_4_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_4of10
        BODO_3P_5_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_5of10
        BODO_3P_6_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_6of10
        BODO_3P_7_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_7of10
        BODO_3P_8_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_8of10
        BODO_3P_9_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_9of10
        BODO_3P_10_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_10of10

  - template: buildscripts/bodo/azure/azure-test-conda-linux-macos.yml
    parameters:
      # Note: name is used later in the buildscripts to determine which version of conda to install
      name: macOS
      ### NOTE: The template doesn't actually support this parameter!
      vmImage: macOS-latest
      useNumbaDev: false
      caching_test: false
      PYTHON_VERSION: 3.10
      matrix:
        BODO_3P_1_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_1of10
        BODO_3P_2_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_2of10
        BODO_3P_3_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_3of10
        BODO_3P_4_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_4of10
        BODO_3P_5_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_5of10
        BODO_3P_6_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_6of10
        BODO_3P_7_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_7of10
        BODO_3P_8_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_8of10
        BODO_3P_9_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_9of10
        BODO_3P_10_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_10of10

  - template: buildscripts/bodo/azure/azure-test-conda-linux-macos.yml
    parameters:
      name: Linux_38py
      useNumbaDev: false
      caching_test: false
      CONDA_ENV: 'bodo'
      PYTHON_VERSION: 3.8
      matrix:
        BODO_3P_1_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_1of10
        BODO_3P_2_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_2of10
        BODO_3P_3_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_3of10
        BODO_3P_4_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_4of10
        BODO_3P_5_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_5of10
        BODO_3P_6_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_6of10
        BODO_3P_7_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_7of10
        BODO_3P_8_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_8of10
        BODO_3P_9_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_9of10
        BODO_3P_10_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_10of10

  - template: buildscripts/bodo/azure/azure-test-conda-linux-macos.yml
    parameters:
      name: Linux_39py
      useNumbaDev: false
      caching_test: false
      CONDA_ENV: 'bodo'
      PYTHON_VERSION: 3.9
      matrix:
        BODO_3P_1_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_1of10
        BODO_3P_2_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_2of10
        BODO_3P_3_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_3of10
        BODO_3P_4_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_4of10
        BODO_3P_5_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_5of10
        BODO_3P_6_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_6of10
        BODO_3P_7_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_7of10
        BODO_3P_8_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_8of10
        BODO_3P_9_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_9of10
        BODO_3P_10_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_10of10
  - template: buildscripts/bodo/azure/azure-test-conda-linux-macos.yml
    parameters:
      # Note: name is used later in the buildscripts to determine which version of conda to install
      name: Linux
      useNumbaDev: false
      caching_test: false
      PYTHON_VERSION: 3.10
      matrix:
        BODO_3P_1_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_1of10
        BODO_3P_2_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_2of10
        BODO_3P_3_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_3of10
        BODO_3P_4_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_4of10
        BODO_3P_5_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_5of10
        BODO_3P_6_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_6of10
        BODO_3P_7_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_7of10
        BODO_3P_8_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_8of10
        BODO_3P_9_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_9of10
        BODO_3P_10_OF_10:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER:  bodo_10of10

  - template: buildscripts/bodo/azure/azure-test-conda-linux-macos.yml
    parameters:
      # Note: name is used later in the buildscripts to determine which version of conda to install
      name: Linux_cache
      useNumbaDev: false
      caching_test: true
      PYTHON_VERSION: 3.10
      matrix:
        TEST_3P:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: ""

  - template: buildscripts/bodo/azure/azure-test-conda-linux-macos.yml
    parameters:
      # Note: name is used later in the buildscripts to determine which version of conda to install
      name: macOS_cache
      ### NOTE: The template doesn't actually support this parameter!
      vmImage: macOS-latest
      useNumbaDev: false
      caching_test: true
      PYTHON_VERSION: 3.10
      matrix:
        TEST_3P:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: ""

  # BodoSQL tests
- stage: Test_BodoSQL_Binary
  displayName: 'Test BodoSQL Binary'
  dependsOn: Build_BodoSQL_Binary
  jobs:

  - template: buildscripts/bodosql/azure/azure-test-conda-linux-macos.yml
    parameters:
      # Note: this name is not important, as we explicitly check uname to determine the os
      # for the bodoSQL tests
      name: BODOSQL_Linux_38py
      ## NOTE: The template doesn't support this!!
      BODO_CHANNEL_NAME: $(BODO_CHANNEL_NAME)
      CONDA_ENV: run_bodo_sql
      PYTHON_VERSION: 3.8
      matrix:
        BODOSQL_3P_1_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_1of7
        BODOSQL_3P_2_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_2of7
        BODOSQL_3P_3_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_3of7
        BODOSQL_3P_4_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_4of7
        BODOSQL_3P_5_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_5of7
        BODOSQL_3P_6_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_6of7
        BODOSQL_3P_7_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_7of7
  - template: buildscripts/bodosql/azure/azure-test-conda-linux-macos.yml
    parameters:
      # Note: this name is not important, as we explicitly check uname to determine the os
      # for the bodoSQL tests
      name: BODOSQL_Linux_39py
      ## NOTE: The template doesn't support this!!
      BODO_CHANNEL_NAME: $(BODO_CHANNEL_NAME)
      CONDA_ENV: run_bodo_sql
      PYTHON_VERSION: 3.9
      matrix:
        BODOSQL_3P_1_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_1of7
        BODOSQL_3P_2_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_2of7
        BODOSQL_3P_3_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_3of7
        BODOSQL_3P_4_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_4of7
        BODOSQL_3P_5_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_5of7
        BODOSQL_3P_6_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_6of7
        BODOSQL_3P_7_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_7of7
  - template: buildscripts/bodosql/azure/azure-test-conda-linux-macos.yml
    parameters:
      # Note: this name is not important, as we explicitly check uname to determine the os
      # for the bodoSQL tests
      name: BODOSQL_Linux_310py
      ## NOTE: The template doesn't support this!!
      BODO_CHANNEL_NAME: $(BODO_CHANNEL_NAME)
      CONDA_ENV: run_bodo_sql
      PYTHON_VERSION: 3.10
      matrix:
        BODOSQL_3P_1_OF_7:
          NP: 3
          PYTEST_MARKER: bodosql_1of7
        BODOSQL_3P_2_OF_7:
          NP: 3
          PYTEST_MARKER: bodosql_2of7
        BODOSQL_3P_3_OF_7:
          NP: 3
          PYTEST_MARKER: bodosql_3of7
        BODOSQL_3P_4_OF_7:
          NP: 3
          PYTEST_MARKER: bodosql_4of7
        BODOSQL_3P_5_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_5of7
        BODOSQL_3P_6_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_6of7
        BODOSQL_3P_7_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_7of7
  - template: buildscripts/bodosql/azure/azure-test-conda-linux-macos.yml
    parameters:
      # Note: this name is not important, as we explicitly check uname to determine the os
      # for the bodoSQL tests
      name: BODOSQL_macOS_38py
      ## NOTE: The template doesn't support this!!
      vmImage: macOS-latest
      ## NOTE: The template doesn't support this!!
      BODO_CHANNEL_NAME: $(BODO_CHANNEL_NAME)
      CONDA_ENV: run_bodo_sql
      PYTHON_VERSION: 3.8
      matrix:
        BODOSQL_3P_1_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_1of7
        BODOSQL_3P_2_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_2of7
        BODOSQL_3P_3_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_3of7
        BODOSQL_3P_4_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_4of7
        BODOSQL_3P_5_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_5of7
        BODOSQL_3P_6_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_6of7
        BODOSQL_3P_7_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_7of7
  - template: buildscripts/bodosql/azure/azure-test-conda-linux-macos.yml
    parameters:
      # Note: this name is not important, as we explicitly check uname to determine the os
      # for the bodoSQL tests
      name: BODOSQL_macOS_39py
      ## NOTE: The template doesn't support this!!
      vmImage: macOS-latest
      ## NOTE: The template doesn't support this!!
      BODO_CHANNEL_NAME: $(BODO_CHANNEL_NAME)
      CONDA_ENV: run_bodo_sql
      PYTHON_VERSION: 3.9
      matrix:
        BODOSQL_3P_1_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_1of7
        BODOSQL_3P_2_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_2of7
        BODOSQL_3P_3_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_3of7
        BODOSQL_3P_4_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_4of7
        BODOSQL_3P_5_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_5of7
        BODOSQL_3P_6_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_6of7
        BODOSQL_3P_7_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_7of7
  - template: buildscripts/bodosql/azure/azure-test-conda-linux-macos.yml
    parameters:
      # Note: this name is not important, as we explicitly check uname to determine the os
      # for the bodoSQL tests
      name: BODOSQL_macOS_310py
      ## NOTE: The template doesn't support this!!
      vmImage: macOS-latest
      ## NOTE: The template doesn't support this!!
      BODO_CHANNEL_NAME: $(BODO_CHANNEL_NAME)
      CONDA_ENV: run_bodo_sql
      PYTHON_VERSION: 3.10
      matrix:
        BODOSQL_3P_1_OF_7:
          NP: 3
          PYTEST_MARKER: bodosql_1of7
        BODOSQL_3P_2_OF_7:
          NP: 3
          PYTEST_MARKER: bodosql_2of7
        BODOSQL_3P_3_OF_7:
          NP: 3
          PYTEST_MARKER: bodosql_3of7
        BODOSQL_3P_4_OF_7:
          NP: 3
          PYTEST_MARKER: bodosql_4of7
        BODOSQL_3P_5_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_5of7
        BODOSQL_3P_6_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_6of7
        BODOSQL_3P_7_OF_7:
          NP: 3
          PYTEST_MARKER:  bodosql_7of7

  - template: buildscripts/bodosql/azure/azure-test-conda-linux-macos.yml
    parameters:
      # Note: this name is not important, as we explicitly pass CACHE_TEST and
      # check uname to determine the os for the bodoSQL tests
      name: BODOSQL_Linux_cache
      ## NOTE: The template doesn't support this!!
      BODO_CHANNEL_NAME: $(BODO_CHANNEL_NAME)
      CONDA_ENV: build_bodo_sql
      PYTHON_VERSION: 3.10
      CACHE_TEST: true
      PYTEST_MARKER: ""
      matrix:
        TEST_3P:
          NP: 3

  - template: buildscripts/bodosql/azure/azure-test-conda-linux-macos.yml
    parameters:
      # Note: this name is not important, as we explicitly pass CACHE_TEST and
      # check uname to determine the os for the bodoSQL tests
      name: BODOSQL_macOS_cache
      ## NOTE: The template doesn't support this!!
      vmImage: macOS-latest
      ## NOTE: The template doesn't support this!!
      BODO_CHANNEL_NAME: $(BODO_CHANNEL_NAME)
      CONDA_ENV: build_bodo_sql
      PYTHON_VERSION: 3.10
      CACHE_TEST: true
      PYTEST_MARKER: ""
      matrix:
        TEST_3P:
          NP: 3

