trigger:
- refs/tags/*

pr: none

schedules:
- cron: "0 15 * * WED"
  displayName: 'Weekly np3 build'
  branches:
    include:
    - main

# Note: we only build the packages that we need for testing on the weekly pipeline (no PiP or ARM)
stages:
- stage: Build_Bodo_BodoSQL_Binary
  displayName: 'Build Bodo and BodoSQL Binary'
  jobs:
  - job: find_suffix
    pool:
      vmImage: macOS-latest
    steps:
    - script: |
        set -eo pipefail
        export BUILD_DATE=`date  +"%Y-%m-%d"`
        export FILE_SUFFIX=built-${BUILD_DATE}
        echo "##vso[task.setvariable variable=fileSuffix;isOutput=true]$FILE_SUFFIX"
      displayName: 'write FILE_SUFFIX'
      name: suffix_step

  # Bodo build:
  # Note: for all the bodo build steps,
  # the name string is used later in the buildscripts to determine which version of conda to install
  - template: buildscripts/azure/azure-build-binary-linux-macos.yml
    parameters:
      name: Linux
      vmImage: ubuntu-latest
      useNumbaDev: false
      platformBuild: false
      weeklyTest: true
  - template: buildscripts/azure/azure-build-binary-linux-macos.yml
    parameters:
      name: macOS
      vmImage: macOS-latest
      useNumbaDev: false
      platformBuild: false
      weeklyTest: true
#  - template: buildscripts/azure/azure-build-binary-windows.yml
#    parameters:
#      name: Windows
#      vmImage: windows-2019
#      useNumbaDev: false
#  - template: buildscripts/azure/azure-build-binary-windows-pip.yml
#    parameters:
#      name: Windows_pip
#      vmImage: windows-2019
#      useNumbaDev: false
#      platformBuild: false

# Note: It is difficult to enforce the exact version of bodo to use for the build, outside of
# modifying the build recipe. Therefore, if we update BodoSQL's build process to require a specific version
# of Bodo, I'm requiring that we update the recipe in buildscripts/bodosql/conda-recipe/meta.yaml,
# and do a mini-release.

  # BodoSQL build:
  - template: buildscripts/bodosql/azure/azure-build-binary.yml
    parameters:
      name: BodoSQL_Conda_Build
      vmImage: ubuntu-latest
      CONDA_ENV: build_bodo_sql
      PYTHON_VERSION: 3.10
  - template: buildscripts/bodosql/azure/azure-build-binary-pip.yml
    parameters:
      name: BodoSQL_Pip_Build
      vmImage: ubuntu-latest
      CONDA_ENV: build_bodo_sql
      PYTHON_VERSION: 3.10

# NOTE: we don't do any builds here, as we assume the previous nightly run has built the needed
# packages and put them on conda

- stage: Test_Bodo_and_BodoSQL_Binary
  displayName: Test Bodo and BodoSQL Binary
  jobs:

  # Bodo tests:
  - template: buildscripts/azure/azure-test-binary-linux-macos.yml
    parameters:
      # Note: name is used later in the buildscripts to determine which version of conda to install
      name: macOS
      vmImage: macOS-latest
      useNumbaDev: false
      caching_test: false
      matrix:
        BODO_3P_1_OF_8:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_1_of_8
        BODO_3P_2_OF_8:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_2_of_8
        BODO_3P_3_OF_8:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_3_of_8
        BODO_3P_4_OF_8:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_4_of_8
        BODO_3P_5_OF_8:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_5_of_8
        BODO_3P_6_OF_8:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_6_of_8
        BODO_3P_7_OF_8:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_7_of_8
        BODO_3P_8_OF_8:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_8_of_8
  - template: buildscripts/azure/azure-test-binary-linux-macos.yml
    parameters:
      # Note: name is used later in the buildscripts to determine which version of conda to install
      name: Linux
      vmImage: ubuntu-latest
      useNumbaDev: false
      caching_test: false
      matrix:
        BODO_3P_1_OF_8:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_1_of_8
        BODO_3P_2_OF_8:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_2_of_8
        BODO_3P_3_OF_8:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_3_of_8
        BODO_3P_4_OF_8:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_4_of_8
        BODO_3P_5_OF_8:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_5_of_8
        BODO_3P_6_OF_8:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_6_of_8
        BODO_3P_7_OF_8:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_7_of_8
        BODO_3P_8_OF_8:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_8_of_8

  - template: buildscripts/azure/azure-test-binary-linux-macos.yml
    parameters:
      # Note: name is used later in the buildscripts to determine which version of conda to install
      name: Linux_cache
      vmImage: ubuntu-latest
      useNumbaDev: false
      caching_test: true
      matrix:
        TEST_3P:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: ""

  - template: buildscripts/azure/azure-test-binary-linux-macos.yml
    parameters:
      # Note: name is used later in the buildscripts to determine which version of conda to install
      name: macOS_cache
      vmImage: macOS-latest
      useNumbaDev: false
      caching_test: true
      matrix:
        TEST_3P:
          NP: 3
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: ""

  # BodoSQL tests

  - template: buildscripts/bodosql/azure/azure-test-binary-linux-macos.yml
    parameters:
      # Note: this name is not important, as we explicitly check uname to determine the os
      # for the bodoSQL tests
      name: BODOSQL_Linux_38py
      vmImage: ubuntu-latest
      BODO_CHANNEL_NAME: $(BODO_CHANNEL_NAME)
      CONDA_ENV: run_bodo_sql
      PYTHON_VERSION: 3.8
      matrix:
        TEST_1P:
          NP: 1
          PYTEST_MARKER: "slow"
  - template: buildscripts/bodosql/azure/azure-test-binary-linux-macos.yml
    parameters:
      # Note: this name is not important, as we explicitly check uname to determine the os
      # for the bodoSQL tests
      name: BODOSQL_Linux_39py
      vmImage: ubuntu-latest
      BODO_CHANNEL_NAME: $(BODO_CHANNEL_NAME)
      CONDA_ENV: run_bodo_sql
      PYTHON_VERSION: 3.9
      matrix:
        TEST_1P:
          NP: 1
          PYTEST_MARKER: "slow"
  - template: buildscripts/bodosql/azure/azure-test-binary-linux-macos.yml
    parameters:
      # Note: this name is not important, as we explicitly check uname to determine the os
      # for the bodoSQL tests
      name: BODOSQL_Linux_310py
      vmImage: ubuntu-latest
      BODO_CHANNEL_NAME: $(BODO_CHANNEL_NAME)
      CONDA_ENV: run_bodo_sql
      PYTHON_VERSION: 3.10
      matrix:
        BODOSQL_3P_PART_1_OF_4:
          NP: 3
          PYTEST_MARKER: bodosql_1_of_4
        BODOSQL_3P_PART_2_OF_4:
          NP: 3
          PYTEST_MARKER: bodosql_2_of_4
        BODOSQL_3P_PART_3_OF_4:
          NP: 3
          PYTEST_MARKER: bodosql_3_of_4
        BODOSQL_3P_PART_4_OF_4:
          NP: 3
          PYTEST_MARKER: bodosql_4_of_4
  - template: buildscripts/bodosql/azure/azure-test-binary-linux-macos.yml
    parameters:
      # Note: this name is not important, as we explicitly check uname to determine the os
      # for the bodoSQL tests
      name: BODOSQL_macOS_38py
      vmImage: macOS-latest
      BODO_CHANNEL_NAME: $(BODO_CHANNEL_NAME)
      CONDA_ENV: run_bodo_sql
      PYTHON_VERSION: 3.8
      matrix:
        TEST_1P:
          NP: 1
          PYTEST_MARKER: "slow"
  - template: buildscripts/bodosql/azure/azure-test-binary-linux-macos.yml
    parameters:
      # Note: this name is not important, as we explicitly check uname to determine the os
      # for the bodoSQL tests
      name: BODOSQL_macOS_310py
      vmImage: macOS-latest
      BODO_CHANNEL_NAME: $(BODO_CHANNEL_NAME)
      CONDA_ENV: run_bodo_sql
      PYTHON_VERSION: 3.9
      matrix:
        TEST_1P:
          NP: 1
          PYTEST_MARKER: "slow"
  - template: buildscripts/bodosql/azure/azure-test-binary-linux-macos.yml
    parameters:
      # Note: this name is not important, as we explicitly check uname to determine the os
      # for the bodoSQL tests
      name: BODOSQL_macOS_39py
      vmImage: macOS-latest
      BODO_CHANNEL_NAME: $(BODO_CHANNEL_NAME)
      CONDA_ENV: run_bodo_sql
      PYTHON_VERSION: 3.10
      matrix:
        BODOSQL_3P_PART_1_OF_4:
          NP: 3
          PYTEST_MARKER: bodosql_1_of_4
        BODOSQL_3P_PART_2_OF_4:
          NP: 3
          PYTEST_MARKER: bodosql_2_of_4
        BODOSQL_3P_PART_3_OF_4:
          NP: 3
          PYTEST_MARKER: bodosql_3_of_4
        BODOSQL_3P_PART_4_OF_4:
          NP: 3
          PYTEST_MARKER: bodosql_4_of_4

  - template: buildscripts/bodosql/azure/azure-test-binary-linux-macos.yml
    parameters:
      # Note: this name is not important, as we explicitly pass CACHE_TEST and
      # check uname to determine the os for the bodoSQL tests
      name: BODOSQL_Linux_cache
      vmImage: ubuntu-latest
      BODO_CHANNEL_NAME: $(BODO_CHANNEL_NAME)
      CONDA_ENV: build_bodo_sql
      PYTHON_VERSION: 3.10
      CACHE_TEST: true
      PYTEST_MARKER: ""
      matrix:
        TEST_3P:
          NP: 3

  - template: buildscripts/bodosql/azure/azure-test-binary-linux-macos.yml
    parameters:
      # Note: this name is not important, as we explicitly pass CACHE_TEST and
      # check uname to determine the os for the bodoSQL tests
      name: BODOSQL_macOS_cache
      vmImage: macOS-latest
      BODO_CHANNEL_NAME: $(BODO_CHANNEL_NAME)
      CONDA_ENV: build_bodo_sql
      PYTHON_VERSION: 3.10
      CACHE_TEST: true
      PYTEST_MARKER: ""
      matrix:
        TEST_3P:
          NP: 3

