trigger:
- refs/tags/*

schedules:
- cron: "0 0 * * 0"
  displayName: 'Weekly Platform Build'
  branches:
    include:
    - main

pr: none

stages:
- stage: Build_Bodo_Conda
  displayName: 'Build Bodo for Conda'
  jobs:

  - template: buildscripts/bodo/azure/azure-build-conda-linux-macos.yml
    parameters:
      name: LinuxForPlatform
      buildMac: false
      pool: ScalingVMSet
      platformBuild: true
      weeklyTest: false
