trigger:
- refs/tags/*

pr: none

schedules:
- cron: "0 5 * * MON-FRI"
  displayName: 'Daily midnight build'
  branches:
    include:
    - master

stages:
- stage: Build_Bodo_BodoSQL_Binary
  displayName: 'Build Bodo and BodoSQL Binary'
  jobs:
  - job: find_suffix
    pool:
      vmImage: macOS-latest
    steps:
    - script: |
        set -eo pipefail
        export BUILD_DATE=`date  +"%Y-%m-%d"`
        export FILE_SUFFIX=built-${BUILD_DATE}
        echo "##vso[task.setvariable variable=fileSuffix;isOutput=true]$FILE_SUFFIX"
      displayName: 'write FILE_SUFFIX'
      name: suffix_step

  # Bodo build:
  # Note: for all the bodo build steps,
  # the name string is used later in the buildscripts to determine which version of conda to install
  - template: buildscripts/azure/azure-build-binary-linux-macos.yml
    parameters:
      name: Linux
      vmImage: ubuntu-latest
      useNumbaDev: false
      platformBuild: false
      weeklyTest: false
  - template: buildscripts/azure/azure-build-binary-linux-macos.yml
    parameters:
      name: macOS
      vmImage: macOS-latest
      useNumbaDev: false
      platformBuild: false
      weeklyTest: false
#  - template: buildscripts/azure/azure-build-binary-windows.yml
#    parameters:
#      name: Windows
#      vmImage: windows-2019
#      useNumbaDev: false
  - template: buildscripts/azure/azure-build-binary-linux-macos.yml
    parameters:
      name: macOS_ARM
      vmImage: macOS-latest
      useNumbaDev: false
      platformBuild: false
      weeklyTest: false
  - template: buildscripts/azure/azure-build-binary-linux-pip.yml
    parameters:
      name: Linux_pip
      vmImage: ubuntu-latest
      useNumbaDev: false
      platformBuild: false
#  - template: buildscripts/azure/azure-build-binary-windows-pip.yml
#    parameters:
#      name: Windows_pip
#      vmImage: windows-2019
#      useNumbaDev: false
#      platformBuild: false
  - template: buildscripts/azure/azure-build-binary-macos-x86-pip.yml
    parameters:
      name: macOS_x86_pip
      vmImage: macOS-latest
      useNumbaDev: false
      platformBuild: false

# Note: It is difficult to enforce the exact version of bodo to use for the build, outside of
# modifying the build recipe. Therefore, if we update BodoSQL's build process to require a specific version
# of Bodo, I'm requiring that we update the recipe in buildscripts/bodosql/conda-recipe/meta.yaml,
# and do a mini-release.

  # BodoSQL build:
  - template: buildscripts/bodosql/azure/azure-build-binary.yml
    parameters:
      name: BodoSQL_Conda_Build
      vmImage: ubuntu-latest
      CONDA_ENV: build_bodo_sql
      PYTHON_VERSION: 3.10
  - template: buildscripts/bodosql/azure/azure-build-binary-pip.yml
    parameters:
      name: BodoSQL_Pip_Build
      vmImage: ubuntu-latest
      CONDA_ENV: build_bodo_sql
      PYTHON_VERSION: 3.10

- stage: Test_Bodo_and_BodoSQL_Binary
  displayName: Test Bodo and BodoSQL Binary
  jobs:

  # Bodo tests:
  - template: buildscripts/azure/azure-test-binary-linux-macos.yml
    parameters:
      # Note: name is used later in the buildscripts to determine which version of conda to install
      name: Linux
      vmImage: ubuntu-latest
      useNumbaDev: false
      caching_test: false
      PYTHON_VERSION: 3.10
      matrix:
        BODO_1P_1_OF_6:
          NP: 1
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_1of6
        BODO_1P_2_OF_6:
          NP: 1
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_2of6
        BODO_1P_3_OF_6:
          NP: 1
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_3of6
        BODO_1P_4_OF_6:
          NP: 1
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_4of6
        BODO_1P_5_OF_6:
          NP: 1
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_5of6
        BODO_1P_6_OF_6:
          NP: 1
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_6of6
        BODO_2P_1_OF_8:
          NP: 2
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_1of8
        BODO_2P_2_OF_8:
          NP: 2
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_2of8
        BODO_2P_3_OF_8:
          NP: 2
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_3of8
        BODO_2P_4_OF_8:
          NP: 2
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_4of8
        BODO_2P_5_OF_8:
          NP: 2
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_5of8
        BODO_2P_6_OF_8:
          NP: 2
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_6of8
        BODO_2P_7_OF_8:
          NP: 2
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_7of8
        BODO_2P_8_OF_8:
          NP: 2
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: bodo_8of8

  - template: buildscripts/azure/azure-test-binary-linux-macos.yml
    parameters:
      # Note: name is used later in the buildscripts to determine which version of conda to install
      name: Linux_cache
      vmImage: ubuntu-latest
      useNumbaDev: false
      caching_test: true
      PYTHON_VERSION: 3.10
      matrix:
        TEST_2P:
          NP: 2
          CONDA_ENV: 'bodo'
          PYTEST_MARKER: ""

  # BodoSQL tests
  - template: buildscripts/bodosql/azure/azure-test-binary-linux-macos.yml
    parameters:
      # Note: this name is not important, as we explicitly check uname to determine the os
      # for the bodoSQL tests
      name: BODOSQL_Linux
      vmImage: ubuntu-latest
      BODO_CHANNEL_NAME: $(BODO_CHANNEL_NAME)
      CONDA_ENV: run_bodo_sql
      PYTHON_VERSION: 3.10
      matrix:
        BODOSQL_1P_1_OF_4:
          NP: 1
          PYTEST_MARKER: bodosql_1of4
        BODOSQL_1P_2_OF_4:
          NP: 1
          PYTEST_MARKER: bodosql_2of4
        BODOSQL_1P_3_OF_4:
          NP: 1
          PYTEST_MARKER: bodosql_3of4
        BODOSQL_1P_4_OF_4:
          NP: 1
          PYTEST_MARKER: bodosql_4of4
        BODOSQL_2P_1_OF_5:
          NP: 2
          PYTEST_MARKER: bodosql_1of5
        BODOSQL_2P_2_OF_5:
          NP: 2
          PYTEST_MARKER: bodosql_2of5
        BODOSQL_2P_3_OF_5:
          NP: 2
          PYTEST_MARKER: bodosql_3of5
        BODOSQL_2P_4_OF_5:
          NP: 2
          PYTEST_MARKER: bodosql_4of5
        BODOSQL_2P_5_OF_5:
          NP: 2
          PYTEST_MARKER: bodosql_5of5

  - template: buildscripts/bodosql/azure/azure-test-binary-linux-macos.yml
    parameters:
      # Note: this name is not important, as we explicitly pass CACHE_TEST and
      # check uname to determine the os for the bodoSQL tests
      name: BODOSQL_Linux_cache
      vmImage: ubuntu-latest
      BODO_CHANNEL_NAME: $(BODO_CHANNEL_NAME)
      CONDA_ENV: build_bodo_sql
      PYTHON_VERSION: 3.10
      CACHE_TEST: true
      PYTEST_MARKER: ""
      matrix:
        TEST_2P:
          NP: 2
