version: 0.2

env:
  git-credential-helper: yes
  
proxy:
    upload-artifacts: no
    logs: no
            
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Entered the install phase...
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      - chmod +x miniconda.sh
      - ./miniconda.sh -b
      - export PATH=$HOME/miniconda3/bin:$PATH

  build:
    commands:
      - echo Entered the build phase...
      - export PATH=$HOME/miniconda3/bin:$PATH
      - conda install -y conda-build anaconda-client conda-verify
      - mkdir build-dir
      - cd build-dir
      - git clone -b master --single-branch https://github.com/Bodo-inc/Bodo.git
      - cd Bodo
      - ./aws_scripts/git_env_var.sh
      - cd buildscripts/bodo-conda-recipe/
      - conda-build . -c bodo.ai -c conda-forge --no-test
      
  post_build:
    commands:
      - echo Entered the post-build phase...
      - export PATH=$HOME/miniconda3/bin:$PATH 
      - cd $CODEBUILD_SRC_DIR
      - mkdir bodo-inc
      - mkdir bodo-inc/linux-64
      - cp ~/miniconda3/conda-bld/linux-64/bodo*.tar.bz2 bodo-inc/linux-64
      - conda index bodo-inc/
      - zip -r bodo-inc.zip bodo-inc

artifacts:
  files:
    - bodo-inc.zip
    - appspec.yml
    - aws_scripts/cleanup.sh
    - aws_scripts/unzip_bodo.sh
    - aws_scripts/install_bodo.sh
    - aws_scripts/run_benchmarks.sh
    - aws_scripts/run_tpch.sh
    - aws_scripts/git_push.sh
  name: Bodo-artifact

