version: 0.2

# Actual buildspec file used to run each CI job where NP =1.
# This file is NOT a template but is shared across the distributed test runs.
# Buildspec Reference: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html


env:
    git-credential-helper: true
    shell: /bin/bash
    variables:
      CONDA_ENV: BodoCodeBuild
      RUN_NIGHTLY: "no"
      RUNTIME: "yes"

phases:
    install:
        commands:
        - echo Entered the install phase...
        - ./buildscripts/aws/CI_if_changes.sh buildscripts/setup_conda.sh
        - ./buildscripts/aws/CI_if_changes.sh buildscripts/aws/test_installs.sh
        - ./buildscripts/aws/CI_if_changes.sh buildscripts/aws/merge_with_master.sh
    build:
        commands:
        - echo Entered the build phase...
        - ./buildscripts/aws/CI_if_changes.sh buildscripts/build.sh
    post_build:
        commands:
        - echo Entered the post-build phase...
        - ./buildscripts/aws/CI_if_changes.sh buildscripts/aws/run_unittests.sh

artifacts:
  files:
    - ./.coverage
  name: $(buildscripts/aws/get_sonar_artifact_name.sh)
