version: 0.2

# Actual buildspec file used to run each CI job where NP =1.
# This file is NOT a template but is shared across the distributed test runs.
# Buildspec Reference: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

env:
  git-credential-helper: true
  shell: /bin/bash
  variables:
    CI_SOURCE: AWS
    CONDA_ENV: BodoCodeBuild
    RUNTIME: "yes"
    PYTHON_VERSION: 3.12

phases:
  # Note: we need to do all the installation and build steps if BodoSQL has been changed
  # but we don't need to run Bodo ci unless Bodo itself has been changed
  install:
    commands:
      - echo Merging with Develop
      - ./buildscripts/aws/CI_if_changes.sh buildscripts/aws/merge_with_develop.sh
      - ./buildscripts/aws/export_env.sh

  build:
    commands:
      - ./buildscripts/aws/CI_if_changes.sh ./buildscripts/build.sh

  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - echo Entered the post-build phase...
      - ./buildscripts/aws/CI_if_changes.sh buildscripts/aws/run_unittests.sh
      - ./buildscripts/aws/CI_if_changes.sh buildscripts/bodosql/test.sh

artifacts:
  files:
    - ./.coverage
    - environment.yml
    - package-list.txt
    - requirements.txt
  name: $(buildscripts/aws/get_sonar_artifact_name.sh)

# https://docs.aws.amazon.com/codebuild/latest/userguide/test-report-pytest.html
reports:
  pytest-report:
    # Search for pytest reports generated in Bodo's repo
    # to view results in AWS CodeBuild console.
    # FYI: pytest result files for Bodo are in Bodo main directory
    # BodoSQL result files are in BodoSQL main directory
    files:
      - "**/pytest-report-*.xml"
    # This is the repo's root directory.
    base-directory: $CODEBUILD_SRC_DIR
    file-format: JUNITXML
