version: 0.2

# Actual buildspec file used to run each CI job where NP =1.
# This file is NOT a template but is shared across the distributed test runs.
# Buildspec Reference: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

env:
  git-credential-helper: true
  shell: /bin/bash
  variables:
    CI_SOURCE: AWS
    CONDA_ENV: BodoCodeBuild
    RUN_NIGHTLY: "no"
    RUNTIME: "yes"
    PYTHON_VERSION: 3.10

phases:

  # Note: we need to do all the installation and build steps if BodoSQL has been changed
  # but we don't need to run Bodo ci unless Bodo itself has been changed
  install:
    commands:
      - echo merging with develop
      - ./buildscripts/bodosql/aws/CI_if_changes.sh buildscripts/aws/merge_with_develop.sh
      - echo Entered the install phase...
      - ./buildscripts/bodosql/aws/CI_if_changes.sh buildscripts/setup_conda.sh
      - ./buildscripts/bodosql/aws/CI_if_changes.sh buildscripts/aws/test_installs.sh
      - ./buildscripts/bodosql/aws/CI_if_changes.sh buildscripts/bodosql/install.sh

  build:
    commands:
      - echo Entered the build phase...
      - ./buildscripts/bodosql/aws/CI_if_changes.sh buildscripts/install_iceberg_connector.sh
        #BodoSQL version of this also builds Bodo and icerberg
      - ./buildscripts/bodosql/aws/CI_if_changes.sh ./buildscripts/bodosql/build.sh

  post_build:
    commands:
      - echo Entered the post-build phase...
      - ./buildscripts/aws/CI_if_changes.sh buildscripts/aws/run_unittests.sh
      - ./buildscripts/bodosql/aws/CI_if_changes.sh buildscripts/bodosql/test.sh

artifacts:
  files:
    - ./.coverage
  name: $(buildscripts/aws/get_sonar_artifact_name.sh)
