version: 0.2

# Link to reference documentation: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

# running on an instance of specs: 145 GB memory, 72 vCPUs

env:
  shell: /bin/bash
  git-credential-helper: true
  variables:
      CONDA_ENV: "BodoCodeBuild"
      RUN_NIGHTLY: "yes"
      RUNTIME: "yes"
      PYTHON_VERSION: 3.10

phases:
    install:
        commands:
        - buildscripts/setup_conda.sh
        - buildscripts/aws/test_installs.sh

    build:
        commands:
        - echo Building Obfuscated Binary
        - buildscripts/aws/build_obfuscated.sh


    post_build:
        commands:
        - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
        - buildscripts/aws/publish_binary.sh
        - buildscripts/install_iceberg_connector.sh
        - buildscripts/aws/run_nightly_tests.sh
