parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
    displayName: 'Use Python $(python.version)'

  - script: |
      set -eo pipefail

      export BODO_VERSION=`python -c "import versioneer; print(versioneer.get_version())"`
      echo "##vso[task.setvariable variable=BODO_VERSION]$BODO_VERSION"
      echo "BODO_VERSION: $BODO_VERSION"

      export IS_RELEASE=`git tag --points-at HEAD`
      echo "##vso[task.setvariable variable=IS_RELEASE]$IS_RELEASE"
      echo "IS_RELEASE: $IS_RELEASE"
    displayName: 'Get Bodo Version and Release Tag (if any)'

  - script: |
      set -eo pipefail
      pip install astunparse
    displayName: 'Prepare to build'

  # For M1, we need to use miniforge to enable cross compilation
  - script: |
      set -eo pipefail
      if [[ "${{ parameters.name }}" = "macOS_ARM" ]]; then
        export MINIFORGE_URL="https://github.com/conda-forge/miniforge/releases/latest/download"
        export MINIFORGE_FILE="Miniforge3-MacOSX-x86_64.sh"
        curl -L -O "${MINIFORGE_URL}/${MINIFORGE_FILE}"
        bash $MINIFORGE_FILE -b -p ${HOME}/miniforge3
        export PATH=$HOME/miniforge3/bin:${PATH}
      else
        if [[ "${{ parameters.name }}" = Linux* ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
        fi
        chmod +x miniconda.sh
        ./miniconda.sh -b
        export PATH=$HOME/miniconda3/bin:${PATH}
      fi
    displayName: 'Setup Miniconda/Miniforge'

  # For M1, need to set MACOSX_DEPLOYMENT_TARGET to 11 before calling setup_osx_sdk, since it defaults to using 10.15
  # if the value is not set. We need at least SDK 11 to do cross compilation.
  - script: |
      set -eo pipefail
      if [[ "${{ parameters.name }}" == "macOS" ]]; then
        buildscripts/setup_osx_sdk.sh
      else
        if [[ "${{ parameters.name }}" = "macOS_ARM" ]]; then
          export MACOSX_DEPLOYMENT_TARGET=${MACOSX_DEPLOYMENT_TARGET:-11.0}
          buildscripts/setup_osx_sdk.sh
        fi
      fi
    displayName: 'Setup OSX SDK'

  - script: |
      set -eo pipefail
      if [[ "${{ parameters.name }}" == "macOS_ARM" ]]; then
        export PATH=$HOME/miniforge3/bin:$PATH
      else
        export PATH=$HOME/miniconda3/bin:$PATH
      fi
      conda install -y flake8
      flake8 bodo
    displayName: 'Flake8'

# 'python<=3.9' is needed, so python 3.10 doesn't get installed by default, which causes issues with
# conda-forge-ci-setup=3
  - script: |
      set -eo pipefail
      if [[ "${{ parameters.name }}" == "macOS_ARM" ]]; then
        export PATH=$HOME/miniforge3/bin:$PATH
      else
        export PATH=$HOME/miniconda3/bin:$PATH
      fi
      conda create -y -n bodo_build conda-build anaconda-client conda-verify 'python<=3.9'
    displayName: 'Create Conda Env'

  # It was taken from code in the Numba feedstock that handles cross compiling,
  # and is necicary to enable it,
  # but I (Keaton) don't fully understand what it's doing
  # I've filed a JIRA issue to figure this out later BE-1568
  - script: |
      set -eo pipefail
      if [[ "${{ parameters.name }}" == "macOS_ARM" ]]; then
        export PATH=$HOME/miniforge3/bin:${PATH}
        export MACOSX_DEPLOYMENT_TARGET=${MACOSX_DEPLOYMENT_TARGET:-11.0}
        export CONDA_BUILD_SYSROOT="/opt/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk"
        source activate bodo_build
        conda install -n bodo_build --quiet --yes "conda-forge-ci-setup=3" -c conda-forge
        setup_conda_rc ./ ./buildscripts/bodo-m1-conda-recipe ./buildscripts/bodo-m1-conda-recipe/conda_build_config.yaml
        /usr/bin/sudo mangle_homebrew
        /usr/bin/sudo -k
        source run_conda_forge_build_setup
      fi
    displayName: 'Handling setup for Cross Compilation'

  - script: |
      set -eo pipefail
      if [[ "${{ parameters.name }}" == "macOS_ARM" ]]; then
        export PATH=$HOME/miniforge3/bin:$PATH
      else
        export PATH=$HOME/miniconda3/bin:$PATH
      fi
      source activate bodo_build
      if [[ $OBFUSCATE == 1 ]]; then
        conda install -y astor -c conda-forge
        cd obfuscation
        ./do_obfuscation.py
      else
        echo "Skipping Obfuscation"
      fi
    displayName: 'Obfuscation'

  - script: |
      set -eo pipefail
      if [[ "${{ parameters.name }}" == "macOS_ARM" ]]; then
        export PATH=$HOME/miniforge3/bin:$PATH
      else
        export PATH=$HOME/miniconda3/bin:$PATH
      fi
      source activate bodo_build
      python rename_to_pyx.py
    displayName: 'Rename py to pyx'

  - script: |
      set -eo pipefail
      if [[ ! -z $IS_RELEASE ]]; then
        ## Remove existing tag if it's a release
        git -c user.name='Bot Herman' -c user.email='bot_herman@bodo.ai' tag -d $IS_RELEASE
      fi

      ## Commit the changes after obfuscation
      git -c user.name='Bot Herman' -c user.email='bot_herman@bodo.ai' add .
      git -c user.name='Bot Herman' -c user.email='bot_herman@bodo.ai' commit --no-verify -a --amend --no-edit

      if [[ ! -z $IS_RELEASE ]]; then
        ## Tag new commit with the old tag, if it's a release
        git -c user.name='Bot Herman' -c user.email='bot_herman@bodo.ai' tag -a $IS_RELEASE -m $IS_RELEASE
      fi
    displayName: 'Amend Commit to remove dirty from version'

  - script: |
      set -eo pipefail
      if [[ "${{ parameters.name }}" == "macOS_ARM" ]]; then
        export PATH=$HOME/miniforge3/bin:$PATH
        export MACOSX_DEPLOYMENT_TARGET=${MACOSX_DEPLOYMENT_TARGET:-11.0}
      else
        export PATH=$HOME/miniconda3/bin:$PATH
        export MACOSX_DEPLOYMENT_TARGET=${MACOSX_DEPLOYMENT_TARGET:-10.15}
      fi
      export CONDA_BUILD_SYSROOT="/opt/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk"
      source activate bodo_build
      if [[ "${{ parameters.name }}" == "macOS_ARM" ]]; then
        cd buildscripts/bodo-m1-conda-recipe/
      else
        cd buildscripts/bodo-conda-recipe/
      fi
      if [[ "${{ parameters.platformBuild }}" == "true" ]]; then
        export CHECK_LICENSE_EXPIRED="0"
        export CHECK_LICENSE_CORE_COUNT="0"
        export CHECK_LICENSE_PLATFORM="1"
      else
        export CHECK_LICENSE_EXPIRED=$(CHECK_LICENSE_EXPIRED)
        export CHECK_LICENSE_CORE_COUNT=$(CHECK_LICENSE_CORE_COUNT)
      fi

      conda-build . -c conda-forge --no-test
    displayName: 'Conda build Bodo'

  - task: DownloadSecureFile@1
    name: secret_file
    displayName: 'Download secrets file'
    inputs:
      secureFile: 'publish_binary_secrets'

  - script: |
      set -eo pipefail
      echo "BODO_VERSION: $BODO_VERSION"
      sudo chmod a+r $(secret_file.secureFilePath)
      sudo cp $(secret_file.secureFilePath) $HOME/secret_file
      cd $(System.DefaultWorkingDirectory)
      mkdir bodo-inc
      echo "IS_RELEASE: $IS_RELEASE"
      export CHECK_LICENSE_EXPIRED=$(CHECK_LICENSE_EXPIRED)
      export OBFUSCATE=$(OBFUSCATE)
      if [[ "${{ parameters.platformBuild }}" == "true" ]]; then
        export CHECK_LICENSE_EXPIRED="0"
        export CHECK_LICENSE_CORE_COUNT="0"
        export CHECK_LICENSE_PLATFORM="1"
        export PLATFORM_DEV_RELEASE=$(PLATFORM_DEV_RELEASE)
      else
        export CHECK_LICENSE_EXPIRED=$(CHECK_LICENSE_EXPIRED)
        export CHECK_LICENSE_CORE_COUNT=$(CHECK_LICENSE_CORE_COUNT)
        export PLATFORM_DEV_RELEASE="false"
      fi
      artifactory_channel=`./buildscripts/azure/get_channel.sh $PLATFORM_DEV_RELEASE`
      echo "artifactory_channel: $artifactory_channel"
      if [[ "${{ parameters.name }}" = Linux* ]]; then
        artifactory_os_dir="linux-64"
      else
        if [[ "${{ parameters.name }}" = "macOS_ARM" ]]; then
          artifactory_os_dir="osx-arm64"
        else
          artifactory_os_dir="osx-64"
        fi
      fi
      echo "artifactory_os_dir: $artifactory_os_dir"
      ./buildscripts/azure/publish_binary.sh $artifactory_channel $artifactory_os_dir $BODO_VERSION
      if [[ "${{ parameters.platformBuild }}" == "true" ]]; then
        ./buildscripts/azure/trigger_ami_build.sh $artifactory_channel $artifactory_os_dir $PLATFORM_DEV_RELEASE $BODO_VERSION
      fi

    displayName: 'publish bodo binary to Artifactory'
