parameters:
  name: ''
  vmImage: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 240
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 11
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
    displayName: 'Use Python $(python.version)'

  - script: |
      set -eo pipefail
      buildscripts/setup_conda.sh
      export PATH=$HOME/miniconda3/bin:$PATH
    displayName: 'Setup Miniconda'

  - script: |
      if [[ "${{ parameters.name }}" == "macOS" ]]; then
        buildscripts/setup_osx_sdk.sh
      fi
    displayName: 'Setup OSX SDK'

  - script: |
      buildscripts/setup_minio.sh
    displayName: 'Setup minio'

  - script: |
      set -eo pipefail
      export PATH=$HOME/miniconda3/bin:$PATH
      source activate $CONDA_ENV
      # s3fs is required by pandas for S3 IO
      # locking fsspec to 0.8 due to compatibility issues with s3fs
      # Cap the botocore version at 1.20.105 because 1.20.106 is incompatable
      # with fsspec.
      conda install -y -c conda-forge fsspec=0.8 boto3 botocore=1.20.105 s3fs
    displayName: 'Setup s3_testing'

  - script: |
      set -eo pipefail
      export PATH=$HOME/miniconda3/bin:$PATH
      source activate $CONDA_ENV
      pip install deltalake
    displayName: 'Setup deltalake testing'

  - script: |
      set -eo pipefail
      export PATH=$HOME/miniconda3/bin:$PATH
      source activate $CONDA_ENV
      conda install -y -c conda-forge pymysql sqlalchemy
    displayName: 'Setup MySQL testing'

  - script: |
      set -eo pipefail
      export PATH=$HOME/miniconda3/bin:$PATH
      source activate $CONDA_ENV
      python setup.py develop
    displayName: 'Build'

  - script: |
      set -eo pipefail
      export PATH=$HOME/miniconda3/bin:$PATH
      source activate $CONDA_ENV
      conda install -y flake8
      flake8 bodo
    displayName: 'Flake8'

  - script: |
      set -eo pipefail
      export PATH=$HOME/miniconda3/bin:$PATH
      source activate $CONDA_ENV
      pip install pytest pytest-azurepipelines pytest-cov
      if [[ ("$NP" -eq 1) && ("${{ parameters.name }}" == "Linux") ]]; then
        python bodo/runtests.py "$NP" -s -v -m "$(PYTEST_MARKER)" --cov-report= --cov=./ bodo/tests/
      else
        python bodo/runtests.py "$NP" -s -v -m "$(PYTEST_MARKER)" bodo/tests/
      fi
    displayName: 'Test'
