# Copyright (C) 2022 Bodo Inc. All rights reserved.
"""
Equivalent of __init__.py for all BodoSQL array kernel files
"""

from bodo.libs.bodosql_array_kernel_utils import *  # noqa
from bodo.libs.bodosql_datetime_array_kernels import *  # noqa
from bodo.libs.bodosql_json_array_kernels import *  # noqa
from bodo.libs.bodosql_numeric_array_kernels import *  # noqa
from bodo.libs.bodosql_other_array_kernels import *  # noqa
from bodo.libs.bodosql_regexp_array_kernels import *  # noqa
from bodo.libs.bodosql_snowflake_conversion_array_kernels import *  # noqa
from bodo.libs.bodosql_string_array_kernels import *  # noqa
from bodo.libs.bodosql_time_array_kernels import *  # noqa
from bodo.libs.bodosql_trig_array_kernels import *  # noqa
from bodo.libs.bodosql_variadic_array_kernels import *  # noqa
from bodo.libs.bodosql_window_agg_array_kernels import *  # noqa

broadcasted_fixed_arg_functions = {
    "abs",
    "acos",
    "acosh",
    "asin",
    "asinh",
    "atan",
    "atan2",
    "atanh",
    "bitand",
    "bitshiftleft",
    "bitnot",
    "bitor",
    "bitshiftright",
    "bitxor",
    "booland",
    "boolnot",
    "boolor",
    "boolxor",
    "cbrt",
    "ceil",
    "change_event",
    "char",
    "cond",
    "contains",
    "conv",
    "cos",
    "cosh",
    "day_timestamp",
    "dayname",
    "degrees",
    "div0",
    "editdistance_no_max",
    "editdistance_with_max",
    "endswith",
    "equal_null",
    "exp",
    "factorial",
    "floor",
    "format",
    "getbit",
    "haversine",
    "initcap",
    "insert",
    "instr",
    "int_to_days",
    "last_day",
    "left",
    "ln",
    "log",
    "log2",
    "log10",
    "lpad",
    "makedate",
    "mod",
    "month_diff",
    "monthname",
    "negate",
    "next_day",
    "nullif",
    "ord_ascii",
    "position",
    "parse_json",
    "power",
    "previous_day",
    "radians",
    "regexp_count",
    "regexp_instr",
    "regexp_like",
    "regexp_replace",
    "regexp_substr",
    "regr_valx",
    "regr_valy",
    "repeat",
    "replace",
    "reverse",
    "right",
    "round",
    "rpad",
    "rtrimmed_length",
    "second_timestamp",
    "sign",
    "sin",
    "sinh",
    "space",
    "split_part",
    "sqrt",
    "square",
    "startswith",
    "strcmp",
    "strtok",
    "substring",
    "substring_index",
    "tan",
    "tanh",
    "to_boolean",
    "to_char",
    "to_date",
    "to_varchar",
    "translate",
    "trunc",
    "try_to_boolean",
    "try_to_date",
    "weekday",
    "width_bucket",
    "year_timestamp",
    "yearofweekiso",
}


broadcasted_variadic_functions = {"coalesce", "decode"}
