package:
  name: bodo-gpu
  version: {{ BODO_VERSION }}

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  script_env:
    # Necessary for sccache to find AWS
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    # Flag for disabling sccache in the build environment
    - DISABLE_SCCACHE_IN_BUILD
  rpaths:
    - lib
    - {{ PREFIX }}/lib
    - {{ SP_DIR }}/pyarrow

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}
    - {{ stdlib("c") }}
    - cuda-version 13.*
    - sccache
    - mold
    - cmake <4.0,>=3.23
    - make
    - ninja

  host:
    - python
    - pip
    - setuptools >=64
    - cython >=3.0
    - setuptools_scm >=8
    - scikit-build-core
    - mpi4py >=4.0
    - cudf >=25.12
    - rmm >=25.12
    - librmm >=25.12
    - pyarrow 21.0.*
    - libarrow 21.0.*
    - numba >=0.60,<0.62.0
    - pandas >=2.2.0
    - cuda-version 13.*
    - openmpi
    - hdf5 * *mpi_openmpi_*
    - h5py
    - aws-sdk-cpp
    - zstd

  run:
    - python
    - cudf >=25.12
    - rmm >=25.12
    - librmm >=25.12
    - pyarrow 21.0.*
    - numba >=0.60,<0.62.0
    - pandas >=2.2.0
    - pytz
    - {{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}

test:
  requires:
    - pytest
