name: Build Bodo from Source
description: Build Bodo and related packages from Source Code
inputs:
  build-all:
    description: 'Build all packages or only Bodo'
    required: false
    default: false
    type: 'boolean'
  environment:
    description: 'The environment to build in/activate (default or default-cuda)'
    required: false
    default: 'default'
    type: 'string'

runs:
  using: "composite"
  steps:
    # -------------------------- Environment Setup -------------------------- #
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: ${{ inputs.environment }}
          activate-environment: true

      # -------------------------- Build Packages --------------------------- #
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::427443013497:role/BodoEngineNightlyRole
          role-session-name: BodoEnginePrCiSession
          role-skip-session-tagging: true

      - name: Build Bodo
        run: |
          if [ "${{ inputs.environment }}" == "default-cuda" ]; then
            pixi run build-bodo-cudf
          else
            pixi run build-bodo
          fi
        shell: bash
        env:
          # We should just use sccache directly on CI
          DISABLE_CCACHE: 1

      - name: Build Remaining
        if: inputs.build-all == 'true'
        shell: bash
        run: |
          pixi run build-bodosql
          pixi run build-iceberg
