---

- name: IPYPARALLEL | Create profile_default directory
  file:
    path: /home/{{ CLUSTER_USER }}/.ipython/profile_default/
    state: directory
    owner: "{{ CLUSTER_USER }}"
    group: "{{ CLUSTER_USER }}"
    mode: "0755"
  tags:
    - ipyparallel

# XXX Move it to /etc so it's default for all users ?
- name: IPYPARALLEL | Create ipcluster_config.py
  copy:
    src: ipcluster_config.py
    dest: /home/{{ CLUSTER_USER }}/.ipython/profile_default/ipcluster_config.py
    owner: "{{ CLUSTER_USER }}"
    group: "{{ CLUSTER_USER }}"
    mode: "0644"
  tags:
    - ipyparallel

