---
- name: Extract Artifact
  unarchive:
    src: "/tmp/bodo-platform-packages.tar.gz"
    dest: "/tmp"
    remote_src: true

- name: IPYPARALLEL | Install Bodo Platform IpyParallel Kernel Package
  command:
    cmd: "/opt/conda/bin/pip install bodo-platform-ipyparallel-kernel /tmp/bodo-platform-ipyparallel-kernel"
  tags:
    - ipyparallel

- name: IPYPARALLEL | Install Bodo-Platform-IPyParallel-Kernel
  command:
    cmd: "/opt/conda/bin/python -m bodo_platform_ipyparallel_kernel.install --sys-prefix"
  tags:
    - ipyparallel

- name: IPYPARALLEL | Clean /tmp Folder
  command:
    cmd: "rm -r /tmp/bodo-platform-utils /tmp/bodo-platform-extensions /tmp/bodo-platform-ipyparallel-kernel"
  tags:
    - ipyparallel
