version: 0.2

# Link to reference documentation: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

env:
  shell: /bin/bash
  git-credential-helper: true
  variables:
      CONDA_ENV: "BodoCodeBuild"
      BODO_CHANNEL_NAME: bodo.ai
      CI_SOURCE: AWS
      RUNTIME: "yes"

phases:
    install:
        commands:
        - ./buildscripts/setup_conda.sh

    build:
        commands:
        - ./buildscripts/bodosql/build.sh

    post_build:
        commands:
        - ./buildscripts/bodosql/aws/run_nightly_tests.sh
