---
- name: IPYTHON | Create profile_default/startup directory
  file:
    path: /home/{{ CLUSTER_USER }}/.ipython/profile_default/startup/
    state: directory
    owner: "{{ CLUSTER_USER }}"
    group: "{{ CLUSTER_USER }}"
    mode: "0755"
  tags:
    - ipython

- name: IPYTHON | Upload 00-bodo-platform-extensions.ipy file
  copy:
    src: load_bodo_platform_extensions_magics.py
    dest: /home/{{ CLUSTER_USER }}/.ipython/profile_default/startup/00-bodo-platform-extensions.ipy
    owner: "{{ CLUSTER_USER }}"
    group: "{{ CLUSTER_USER }}"
    mode: "0755"
  tags:
    - ipython
