category: main
channels:
  - conda-forge

platforms:
  - osx-arm64
  - osx-64
  - linux-64

dependencies:
  - setuptools >=64
  - setuptools_scm >=8
  - cython >=3.0,<3.1
  - boost-cpp =1.82
  - fmt =10.2

  # C++
  - clang_osx-arm64 =16    #[arm64]
  - clangxx_osx-arm64 =16  #[arm64]
  - clang_osx-64 =16       #[osx64]
  - clangxx_osx-64 =16     #[osx64]
  - gcc_linux-64>=9        #[linux64]
  - gxx_linux-64>=9        #[linux64]

  # Dev Dependencies
  - cmake
  - make
  - ccache
  - sccache
