category: main
channels:
  - conda-forge

platforms:
  - osx-arm64
  - osx-64
  - linux-64

dependencies:
  - setuptools
  - cython <3.0
  - boost-cpp =1.82

  # C++
  - clang_osx-arm64    #[arm64]
  - clangxx_osx-arm64  #[arm64]
  - clang_osx-64       #[osx64]
  - clangxx_osx-64     #[osx64]
  - gcc_linux-64>=9    #[linux64]
  - gxx_linux-64>=9    #[linux64]

  # Dev Dependencies
  - cmake
  - make
  - ccache
