category: dev
channels:
  - conda-forge

platforms:
  - osx-arm64
  - osx-64
  - linux-64

dependencies:
  # Build Python
  - setuptools >=64
  - setuptools_scm >=8
  - cython >=3.0,<3.1
  - scikit-build-core

  # Build C++
  - cmake
  - ninja
  - make
  - ccache
  - sccache

  # C++ Compilers
  - clang_osx-arm64 =16    #[arm64]
  - clangxx_osx-arm64 =16  #[arm64]
  - clang_osx-64 =16       #[osx64]
  - clangxx_osx-64 =16     #[osx64]
  - gcc_linux-64>=9        #[linux64]
  - gxx_linux-64>=9        #[linux64]

  # Build Tools
  - clang-tools =16        #[osx64]
  - clang-tools =16        #[arm64]

  # C++ Deps
  - boost-cpp =1.84
  - fmt =10.1

  # BodoSQL or Iceberg
  # PySpark 3.5 is necessary for Python 3.12
  - maven
  - pyspark=3.5
  - mmh3
  # Install avro to enable reading avro files in Iceberg testing.
  - avro

  # Excel
  - xlrd
  - xlsxwriter
  - openpyxl

  # Testing and CI
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-timeout
  - pytest-azurepipelines
  - flaky
  - ruff
  - credstash

  # Other Deps
  - pyyaml
  - psutil

  # Developer tools
  - pre-commit

  # For deltalake testing
  # As of 2023-10-06, deltalake requires pyarrow <=12.0.0
  # - pip:
  #   - deltalake

  # Future ML Libraries
  # Used to be installed on AWS CIs
  # - pytorch=1.9
  # - bokeh=2.3
  # - torchvision=0.10
  # - tensorflow
  # - pip:
  #   - horovod
