category: dev
channels:
  - bodo.ai
  - conda-forge

platforms:
  - osx-arm64
  - osx-64
  - linux-64

dependencies:
  # Build Python
  - setuptools >=64
  - setuptools_scm >=8
  - cython >=3.0,<3.1
  - scikit-build-core

  # Build C++
  - cmake
  - ninja
  - make
  - ccache
  - sccache

  # C++ Compilers
  - clang_osx-arm64 =19    #[arm64]
  - clangxx_osx-arm64 =19  #[arm64]
  - clang_osx-64 =19       #[osx64]
  - clangxx_osx-64 =19     #[osx64]
  - gcc_linux-64>=9        #[linux64]
  - gxx_linux-64>=9        #[linux64]

  # Build Tools
  - clang-tools =19        #[osx64]
  - clang-tools =19        #[arm64]

  # C++ Deps
  - boost-cpp =1.85

  # BodoSQL or Iceberg
  - maven         # For building
  # PySpark for most BodoSQL and Iceberg tests
  # PySpark 3.5 is necessary for Python 3.12
  - pyspark=3.5   # For most testing
  # DuckDB & SQLGlot for some BodoSQL tests
  # TODO: Migrate more to DuckDB
  # For better compatibility than Spark
  - sqlglot
  - duckdb
  # Iceberg Testing
  - mmh3
  - avro

  # Copied into bodo/mpi4py
  - mpi4py ~= 3.1

  # Excel
  - xlrd
  - xlsxwriter
  - openpyxl

  # Testing and CI
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-timeout
  - pytest-azurepipelines
  - flaky
  - ruff
  - credstash

  # Other Deps
  - pyyaml
  - psutil
  - bs4

  # Developer tools
  - pre-commit

  # For deltalake testing
  # As of 2023-10-06, deltalake requires pyarrow <=12.0.0
  # - pip:
  #   - deltalake

  # Future ML Libraries
  # Used to be installed on AWS CIs
  # - pytorch=1.9
  # - bokeh=2.3
  # - torchvision=0.10
  # - tensorflow
  # - pip:
  #   - horovod
