# Copied from BodoSQL
package:
  name: bodo-azurefs-sas-token-provider
  version: 1.0

source:
  path: ../../../azurefs-sas-token-provider

build:
  noarch: python

requirements:
  host:
    - python >=3.8,<3.11
    # setuptools>=65 removes the msvc compilers that
    # distutils/extension uses.
    # TODO[BE-3467]: remove distutils
    - setuptools <60
    - openjdk >=9.0,<12
    - maven
    - ninja

  run:
    - python >=3.8,<3.11
    - openjdk >=9.0,<12

about:
home: https://bodo.ai/
license: Proprietary
license_file: LICENSE.md
summary: Bodo AzureFS SAS Token Provider
