# Copied from BodoSQL
package:
  name: bodo-azurefs-sas-token-provider
  version: 1.0

source:
  path: ../../../azurefs-sas-token-provider

build:
  noarch: python

requirements:
  host:
    - python >=3.10,<3.13
    - setuptools
    - openjdk >=9.0,<12
    - maven
    - ninja

  run:
    - python >=3.10,<3.13
    - openjdk >=9.0,<12

about:
home: https://bodo.ai/
license: Proprietary
license_file: LICENSE
summary: Bodo AzureFS SAS Token Provider
