package:
  name: bodo
  version: {{ BODO_VERSION }}

source:
   path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  script_env:
    - IS_BODO_PLATFORM
    - BUILD_WITH_V8
    # Necessary for sccache to find AWS
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    # Flag for disabling sccache in the build environment
    - DISABLE_SCCACHE_IN_BUILD
  rpaths:
    - lib
    - {{ PREFIX }}/lib
    - {{ SP_DIR }}/pyarrow

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sccache

  host:
    - python
    - pip

    # Build Dependencies
    - setuptools >=64
    - cython >=3.0
    - setuptools_scm >=8
    - scikit-build-core
    - cmake
    - make
    - ninja
    - mpi4py ~= 4.0
    - numba =0.61.2
    # Compatible with Numba requirements.
    # Resolves build issues on nightly
    - numpy >=1.24
    - pandas >=2.2
    - fsspec >=2021.09
    - libarrow =19.0.0
    - pyarrow =19.0.0
    - libboost-headers =1.85  # [not win]
    - libboost-devel =1.85    # [win]
    - hdf5 >=1.14.3,<1.14.4.0a0=mpi_mpich_* # [not win]
    - hdf5 >=1.14.3,<1.14.4.0a0=*mpi_impi_* # [win]
    - h5py
    - mpich 4.1.*=h*        # [not win]
    - impi-devel            # [win64]
    - requests
    # Corresponding dependency is automatically added in reqs/run.
    - aws-sdk-cpp <=1.11.485
    - zstd<=1.5.6
    - cloudpickle >=3.0

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas >=2.2
    - fsspec >=2021.09
    - pyarrow =19.0.0
    - numba 0.61.2
    - mpich 4.1.*=h* # [not win]
    - requests
    - zstd<=1.5.6
    - cloudpickle >=3.0
    - psutil

  # run_constrained means these packages are not required deps
  # but will restrict them if they are present in the conda env.
  run_constrained:
    - numpy >=1.24
    - s3fs >=2022.1.0
    - adlfs >=2022.1.0
    - pyiceberg >=0.9
    - boto3 *
    - mypy-boto3-glue *

test:
  imports:
    - bodo
  source_files:
    - examples/Misc/misc_pi.py

about:
  home: https://bodo.ai
  license: Apache-2.0
  license_file: LICENSE
  summary: High-Performance Python Compute Engine for Data and AI
