{% set gpu_enabled = gpu == "true" %}
{% set platform_enabled = is_platform == "true" %}
# Platform requires PyArrow 22 for compatibility with PyDough,
# https://github.com/bodo-ai/PyDough/blob/85214a31a9212a9ca503751ee62a84a5eaf59f22/pyproject.toml#L24
{% set pyarrow_version = "22.0" if platform_enabled else "24.0" %}
{% if win %}
    {% set mpi_impl = "impi" %}
    {% set mpi_build_pkg = "impi-devel" %}
    {% set mpi_run_pkg = "impi_rt" %}
{% elif osx or (gpu_enabled and not platform_enabled) %}
    {% set mpi_impl = "openmpi" %}
    {% set mpi_build_pkg = "openmpi" %}
    {% set mpi_run_pkg = "openmpi" %}
{% else %}
    {% set mpi_impl = "mpich" %}
    {% set mpi_build_pkg = "mpich" %}
    {% set mpi_run_pkg = "mpich" %}
{% endif %}

package:
  name: bodo
  version: {{ BODO_VERSION }}

source:
   path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  string: "py{{ PY_VER }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ 'cuda' if gpu_enabled else 'cpu' }}"
  script_env:
    - IS_BODO_PLATFORM
    - BUILD_WITH_V8
    # Necessary for sccache to find AWS
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    # Flag for disabling sccache in the build environment
    - DISABLE_SCCACHE_IN_BUILD
  rpaths:
    - lib
    - {{ PREFIX }}/lib
    - {{ SP_DIR }}/pyarrow

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sccache
    - mold  # [linux]
    - cmake <4.0,>=3.23
    - make
    - ninja
    - {{ compiler('cuda') }}  # [gpu]

  host:
    - python {{ PY_VER }}
    # Avoid no-GIL Python (*_cp314t) in build environment for compatibility with platform.
    - python_abi {{ PY_VER }} *_cp{{ PY_VER|replace('.', '') }}
    - pip

    # Build Dependencies
    - setuptools >=64
    - cython >=3.0
    - setuptools_scm >=8
    - scikit-build-core
    - mpi4py >=4.0
    - numba >=0.62,<0.66
    # Compatible with Numba requirements.
    # Resolves build issues on nightly
    - numpy >=1.24
    - libarrow ={{ pyarrow_version }}  # [not win]
    - pyarrow ={{ pyarrow_version }}
    - libboost-headers          # [not win]
    - libboost-devel            # [win]
    # Corresponding dependency is automatically added in reqs/run.
    - aws-sdk-cpp
    - zstd

    - hdf5 * *mpi_{{ mpi_impl }}_*
    - h5py

    - {{mpi_build_pkg}}

    # GPU dependencies
    # This pin is necessary to avoid compatibility issues
    - cudf ={{ rapids_version }}        # [gpu]
    - rmm ={{ rapids_version }}         # [gpu]
    - librmm ={{ rapids_version }}      # [gpu]
    - cuda-version 13.*                 # [gpu]
    - cuda-nvml-dev                     # [gpu]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas >=2.2
    - fsspec >=2021.09
    - mpi4py >=4.0
    - pyarrow ={{ pyarrow_version }}
    - numba >=0.62,<0.66

    - {{ mpi_run_pkg }}

    - requests
    - zstd
    - cloudpickle >=3.0
    - psutil
    - pytz

    # GPU dependencies
    - cudf ={{ rapids_version }}                  # [gpu]
    - rmm ={{ rapids_version }}                   # [gpu]
    - librmm ={{ rapids_version }}                # [gpu]

    # Constrain CUDA version to the same major version used in the build environment
    - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}  # [gpu]

  # run_constrained means these packages are not required deps
  # but will restrict them if they are present in the conda env.
  run_constrained:
    - numpy >=1.24
    - s3fs >=2022.1.0
    - adlfs >=2022.1.0
    - pyiceberg >=0.10

test:
  imports:
    - bodo
  source_files:
    - examples/Misc/misc_pi.py

about:
  home: https://bodo.ai
  license: Apache-2.0
  license_file: LICENSE
  summary: High-Performance Python Compute Engine for Data and AI
