package:
  name: bodo
  version: {{ BODO_VERSION }}

source:
   path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  script_env:
    - IS_BODO_PLATFORM
    - BUILD_WITH_V8
    # Necessary for sccache to find AWS
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    # Flag for disabling sccache in the build environment
    - DISABLE_SCCACHE_IN_BUILD
  rpaths:
    - lib
    - {{ PREFIX }}/lib
    - {{ SP_DIR }}/pyarrow

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sccache
    - mold  # [linux]

  host:
    - python
    - pip

    # Build Dependencies
    - setuptools >=64
    - cython >=3.0
    - setuptools_scm >=8
    - scikit-build-core
    - cmake <4.0,>=3.23
    - make
    - ninja
    - mpi4py >=4.0
    - numba >=0.62,<0.64
    # Compatible with Numba requirements.
    # Resolves build issues on nightly
    - numpy >=1.24
    - libarrow =23.0
    - pyarrow =23.0
    - libboost-headers          # [not win]
    - libboost-devel            # [win]
    - hdf5 * *mpi_mpich_*       # [not win and not osx]
    - hdf5 * *mpi_openmpi_*     # [osx]
    - hdf5 * *mpi_impi_*        # [win]
    - h5py
    - mpich                     # [not win and not osx]
    - openmpi                   # [osx]
    - impi-devel                # [win64]
    # Corresponding dependency is automatically added in reqs/run.
    - aws-sdk-cpp
    - zstd
    - pytz

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas >=2.2
    - pytz
    - fsspec >=2021.09
    - pyarrow =23.0
    - numba >=0.62,<0.64
    - requests
    - pytz
    - zstd
    - cloudpickle >=3.0
    - psutil
    - pytz

  # run_constrained means these packages are not required deps
  # but will restrict them if they are present in the conda env.
  run_constrained:
    - numpy >=1.24
    - s3fs >=2022.1.0
    - adlfs >=2022.1.0
    - pyiceberg >=0.10

test:
  imports:
    - bodo
  source_files:
    - examples/Misc/misc_pi.py

about:
  home: https://bodo.ai
  license: Apache-2.0
  license_file: LICENSE
  summary: High-Performance Python Compute Engine for Data and AI
