package:
  name: bodo
  version: {{ BODO_VERSION }}

source:
   path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  script_env:
    - IS_BODO_PLATFORM
    - BUILD_WITH_V8
    # Necessary for sccache to find AWS
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    # Flag for disabling sccache in the build environment
    - DISABLE_SCCACHE_IN_BUILD
  rpaths:
    - lib
    - {{ PREFIX }}/lib
    - {{ SP_DIR }}/pyarrow

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sccache

  host:
    - python
    - pip

    # Build Dependencies
    - setuptools >=64
    - cython >=3.0
    - setuptools_scm >=8
    - scikit-build-core
    - cmake <4.0,>=3.23
    - make
    - ninja
    - mpi4py >=4.0,<4.1
    - numba =0.61.2
    # Compatible with Numba requirements.
    # Resolves build issues on nightly
    - numpy >=1.24
    - libarrow =19.0
    - pyarrow =19.0
    - libboost-headers    # [not win]
    - libboost-devel      # [win]
    - hdf5 >=1.14.3,<1.14.4.0a0
    - hdf5 * mpi_mpich_*        # [not win]
    - hdf5 * *mpi_impi_*        # [win]
    - h5py
    # Necessary to prevent hangs on Macos
    - mpich 4.1.*               # [not win]
    - impi-devel                # [win64]
    # Corresponding dependency is automatically added in reqs/run.
    - aws-sdk-cpp <=1.11.485
    - zstd

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas >=2.2
    - fsspec >=2021.09
    - pyarrow =19.0
    - numba 0.61.2
    - mpich 4.1.*   # [not win]
    - requests
    - zstd
    - cloudpickle >=3.0
    - psutil

  # run_constrained means these packages are not required deps
  # but will restrict them if they are present in the conda env.
  run_constrained:
    - numpy >=1.24
    - s3fs >=2022.1.0
    - adlfs >=2022.1.0
    - pyiceberg >=0.9

test:
  imports:
    - bodo
  source_files:
    - examples/Misc/misc_pi.py

about:
  home: https://bodo.ai
  license: Apache-2.0
  license_file: LICENSE
  summary: High-Performance Python Compute Engine for Data and AI
