CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.15.sdk        # [osx]

# we only test python 3.10 in nightly, no need to build all versions
python:
  - 3.10

numpy:
  - 1.21

c_compiler_version:    # [osx]
  - 12.0.1             # [osx]
cxx_compiler_version:  # [osx]
  - 12.0.1             # [osx]
