
# Source: kube-openmpi/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-bodo-cluster
  labels:
    app: my-bodo-test
spec:
  selector:
    app: my-bodo-test
  clusterIP: None
  ports:
  - name: dummy # Actually, no port is needed.
    port: 1234
    targetPort: 1234

---
# Source: kube-openmpi/templates/mpi-cluster.yaml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-bodo-cluster-worker
  labels:
    app: my-bodo-test
    role: worker
spec:
  selector:
    matchLabels:
      app: my-bodo-test
      role: worker
  serviceName: my-bodo-cluster
  podManagementPolicy: Parallel
  replicas: 2
  template:
    metadata:
      labels:
        app: my-bodo-test
        role: worker
    spec:
      securityContext:
        null
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
         claimName: pv-claim-data
         readOnly: true
      containers:
      - name: mpi-worker
        image: "ehsantn/bodo:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2022
        volumeMounts:
          - mountPath: "/data"
            name: task-pv-storage

        resources:
          null
