package:
    name: bodosql
    version: {{ environ.get('BODOSQL_VERSION') }} 

source:
    path: ../../../BodoSQL

build:
    noarch: python

requirements:
    host:
        - python >=3.10,<3.13
        - setuptools >=64
        - setuptools_scm >=8
        - openjdk >=11.0, <18
        - maven
        - bodo  {{ BODOSQL_VERSION }}

    run:
        - openjdk >=11.0, <18
        - bodo  {{ BODOSQL_VERSION }}
        - py4j ==0.10.9.7
        - python >=3.10,<3.13


test:
    imports:
        - bodosql
    files:
        - test.py


about:
home: https://bodo.ai/
license: Proprietary
license_file: LICENSE.md
summary: Bodo SQL Engine
