package:
    name: bodosql
    version: {{ BODOSQL_VERSION }}

source:
    path: ../../../BodoSQL

build:
    noarch: python

requirements:
    host:
        - python >=3.8,<3.11
        - setuptools
        - openjdk >=9.0
        - maven
        - ninja
        - bodo =2022.7.*

    run:
        - openjdk >=9.0
        - bodo =2022.7.*
        - py4j
        - python >=3.8,<3.11


test:
    imports:
        - bodosql


about:
home: https://bodo.ai/
license: Proprietary
license_file: LICENSE.md
summary: Bodo SQL Engine
