package:
    name: bodosql
    version: {{ environ.get('BODOSQL_VERSION') }} 

source:
    path: ../../../BodoSQL

build:
    noarch: python

requirements:
    host:
        - python >=3.9,<3.14
        - setuptools >=64
        - setuptools_scm >=8
        - openjdk 17
        - maven
        - bodo  {{ BODOSQL_VERSION }}

    run:
        - openjdk 17
        - bodo  {{ BODOSQL_VERSION }}
        - py4j ==0.10.9.9
        - python >=3.9,<3.14


test:
    imports:
        - bodosql
    files:
        - test.py


about:
home: https://bodo.ai/
license: Apache-2.0
license_file: LICENSE
summary: Bodo SQL Engine
