package:
    name: bodosql
    version: {{ BODOSQL_VERSION }}

source:
    path: ../../../BodoSQL

build:
    noarch: python

requirements:
    host:
        - python >=3.8,<3.12
        # setuptools>=65 removes the msvc compilers that
        # distutils/extension uses.
        # TODO[BE-3467]: remove distutils
        - setuptools <63
        - openjdk >=9.0, <12
        - maven
        - bodo {{ BODO_VERSION }}

    run:
        - openjdk >=9.0, <12
        - bodo {{ BODO_VERSION }}
        - py4j ==0.10.9.7
        - python >=3.8,<3.12


test:
    imports:
        - bodosql


about:
home: https://bodo.ai/
license: Proprietary
license_file: LICENSE.md
summary: Bodo SQL Engine
