package:
    name: bodosql
    version: {{ BODOSQL_VERSION }}

source:
    path: ../../../BodoSQL

build:
    noarch: python

requirements:
    host:
        - python >=3.10,<3.13
        - setuptools >=64
        - setuptools_scm >=8
        - openjdk >=9.0, <12
        - maven
        - bodo {{ BODO_VERSION }}

    run:
        - openjdk >=9.0, <12
        - bodo {{ BODO_VERSION }}
        - py4j ==0.10.9.7
        - python >=3.10,<3.13


test:
    imports:
        - bodosql
    files:
        - test.py


about:
home: https://bodo.ai/
license: Proprietary
license_file: LICENSE.md
summary: Bodo SQL Engine
