package:
    name: bodosql
    version: {{ BODOSQL_VERSION }}

source:
    path: ../../../BodoSQL

build:
    noarch: python

requirements:
    host:
        - python >=3.8,<3.11
        # setuptools>=65 removes the msvc compilers that
        # distutils/extension uses.
        # TODO[BE-3467]: remove distutils
        - setuptools <60
        - openjdk >=9.0, <12
        - maven
        - ninja
        - bodo =2022.9.*

    run:
        - openjdk >=9.0
        - bodo =2022.9.*
        - py4j
        - python >=3.8,<3.11


test:
    imports:
        - bodosql


about:
home: https://bodo.ai/
license: Proprietary
license_file: LICENSE.md
summary: Bodo SQL Engine
