---
- name: INTEL MPI | Uninstall MPICH if it's installed
  shell: |
    /opt/conda/bin/conda list mpich | grep -q mpich
    if [[ $? -eq 0 ]]; then
      /opt/conda/bin/conda remove mpich mpi --force --quiet --yes
    else
      echo "mpich not found. Skipping..."
    fi
  tags:
    - intel-mpi

- name: INTEL MPI | Uninstall UCX from Conda
  shell: |
    /opt/conda/bin/conda list ucx | grep -q ucx
    if [[ $? -eq 0 ]]; then
      /opt/conda/bin/conda remove ucx --force --quiet --yes
    else
      echo "ucx not found. Skipping..."
    fi
  tags:
    - intel-mpi

- name: INTEL MPI | Download Intel MPI Script
  get_url:
    url: "{{ INTELMPI_INSTALL_LINK }}"
    dest: /tmp
    mode: 0755
  tags:
    - intel-mpi

- name: INTEL MPI | Install Intel MPI
  command:
    chdir: "/tmp"
    cmd: "/tmp/{{ INTELMPI_SCRIPT }} -s -a -s --eula accept"
  tags:
    - intel-mpi

- name: INTEL MPI | Remove Intel-MPI Script
  ansible.builtin.file:
    path: /tmp/{{ INTELMPI_SCRIPT }}
    state: absent
  tags:
    - intel-mpi

- name: INTEL MPI | Insert a line at the end of a bashrc/bash_profile.
  lineinfile:
    path: "/home/{{ CLUSTER_USER }}/{{ item }}"
    line: source /opt/intel/oneapi/setvars.sh &> /dev/null
  with_items:
    - .bashrc
    - .bash_profile
  tags:
    - intel-mpi

- name: INTEL MPI | Insert ENVs to the End of .bashrc/.bash_profile
  lineinfile:
    path: "/home/{{ CLUSTER_USER }}/{{ item }}"
    line: export FI_EFA_FORK_SAFE=1
  with_items:
    - .bashrc
    - .bash_profile
  tags:
    - intel-mpi

- name: INTEL MPI | Obtain current PATH
  shell: |
    source /opt/intel/oneapi/setvars.sh &> /dev/null
    echo $PATH
  register: path_contents
  tags:
    - intel-mpi

- name: INTEL MPI | Upload /etc/environment
  template:
    dest: /etc/environment
    src: environment.j2
    owner: root
    group: root
    mode: '0644'
  tags:
    - intel-mpi

- name: INTEL MPI | Insert Environment Variables at the end of a bashrc
  blockinfile:
    path: "/home/{{ CLUSTER_USER }}/.bashrc"
    insertbefore: '.*'
    marker: "#<!-- {mark} Env Variables for Configuring Intel MPI -->"
    block: |
      export I_MPI_ADJUST_ALLREDUCE=4
      export I_MPI_ADJUST_REDUCE=3
  tags:
    - intel-mpi

