---
- hosts: localhost
  connection: local
  gather_facts: true
  become: yes
  vars_files:
    - ./vars/common.yaml
    - ./vars/conda.yaml
    - ./vars/jupyter.yaml
    - ./vars/bodo.yaml
  roles:
    - common
    - conda
    - jupyter
