package:
  name: bodo
  version: {{ BODO_VERSION }}

source:
   path: ../..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  script_env:
  - CHECK_LICENSE_EXPIRED
  - CHECK_LICENSE_CORE_COUNT

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - setuptools
    - numba
    - numpy
    - cython
    - pandas 1.2.0
    - fsspec
    - pyarrow =3.0.0
    - boost-cpp =1.74.0
    - hdf5 * mpi_mpich_* # [not win]
    - h5py
    - mpich =3.3.2=h* # [not win]
    - impi-devel # [win]
    - impi_rt # [win]
    - vc # [win]
    - vs2015_runtime # [win]
    - vs2015_win-64 # [win]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas 1.2.0
    - fsspec
    - pyarrow =3.0.0
    - boost-cpp =1.74.0
    - numba
    - openjdk =8
    - sqlalchemy
    - mpich =3.3.2=h* # [not win]
    - mpi4py
    - impi_rt # [win]
    - vs2015_runtime # [win]
    - vs2015_win-64 # [win]


test:
  imports:
    - bodo
  source_files:
    - examples/pi.py


about:
  home: https://bodo.ai
  license: Proprietary
  license_file: LICENSE.md
  summary: Python Supercomputing Analytics Platform
