CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.15.sdk        # [osx and x86]
  - /opt/MacOSX11.0.sdk         # [osx and arm64]

MACOSX_SDK_VERSION:             # [osx and x86]
  - "10.15"                     # [osx and x86]

MACOSX_DEPLOYMENT_TARGET:       # [osx]
  - 10.15                       # [osx and x86]
  - 11.0                        # [osx and arm64]

SDKROOT:                        # [osx and arm64]
  - /opt                        # [osx and arm64]

c_compiler_version:    # [osx]
  - 19                 # [osx]
cxx_compiler_version:  # [osx]
  - 19                 # [osx]


# We only test python 3.12 in nightly, no need to build all versions
python:
  - 3.12

numpy:
  - 1.23
