# Only applies to Linux builds, because we need to restrict
# GCC to v12 for manylinux_2_28 compatibility
# https://github.com/pypa/manylinux
numpy:
  - 1.23

c_compiler_version:
  - 12
cxx_compiler_version:
  - 12

# TODO: find a way to restrict the libstdcxx-ng version to 12 with a variant file.
# Currently this can't be done because libstdcxx-ng has a "-" in the package name.

