CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.15.sdk        # [osx]

# we build python 3.10/3.11/3.12 for releases
python:
  - 3.10
  - 3.11
  - 3.12

numpy:
  - 1.23

# TODO: Remove when libcxx 17 is available on conda-forge
# Clang 17 doesn't support libcxx 16, so we need to force-use Clang 16
c_compiler_version:    # [osx]
  - 16                 # [osx]
cxx_compiler_version:  # [osx]
  - 16                 # [osx]
