CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.15.sdk      # [osx and x86]
  - /opt/MacOSX11.0.sdk       # [osx and arm64]

# we build python 3.10/3.11/3.12 for releases
python:
  - 3.10
  - 3.11
  - 3.12

numpy:
  - 1.23

c_compiler_version:    # [osx]
  - 19                 # [osx]
cxx_compiler_version:  # [osx]
  - 19                 # [osx]

