---
- name: CONDA | Download mambaforge installation script
  get_url:
    url: "{{ URL_MAMBAFORGE }}"
    dest: /tmp/mambaforge.sh
    mode: "0440"
  tags:
    - conda

- name: CONDA | Install mambaforge
  command:
    cmd: /bin/bash /tmp/mambaforge.sh -b -f -p /opt/conda
    creates: /opt/conda
  tags:
    - conda

# Note that upgrade to Python 3.10 upgrades conda.
- name: CONDA | Update python depending on variable
  when: "PYTHON_VERSION | length > 0"
  command:
    cmd: "/opt/conda/bin/mamba install --yes python={{ PYTHON_VERSION }} -c conda-forge"
  tags:
    - conda

- name: CONDA | Obtain current PATH before manipulations
  shell: |
    echo $PATH
  register: path_contents
  tags:
    - conda

- name: CONDA | Upload /etc/environment
  template:
    dest: /etc/environment
    src: environment.j2
    owner: root
    group: root
    mode: "0644"
  tags:
    - conda

- name: CONDA | Insert a line at the end of a bashrc/bash_profile.
  lineinfile:
    path: "/home/{{ CLUSTER_USER }}/.bashrc"
    line: "PATH={{ conda_python_path }}:$PATH"
    insertbefore: ".*"
    firstmatch: yes
  tags:
    - conda

- name: CONDA | Activate Conda Environment in .bashrc
  blockinfile:
    path: "/home/{{ CLUSTER_USER }}/.bashrc"
    insertbefore: ".*"
    marker: "#<!-- {mark} Activate Conda Env -->"
    block: |
      . /opt/conda/etc/profile.d/conda.sh
      conda activate
  tags:
    - conda


- name: CONDA | Update mamba
  command:
    cmd: "/opt/conda/bin/mamba update --force mamba --quiet --yes"
  tags:
    - conda
