parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
    displayName: 'Use Python $(python.version)'

  - script: |
      pip install astunparse
      chmod +x buildscripts/remove_docstring.py
    displayName: 'Prepare to build'

  - powershell: |
        Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
        Write-Host "##vso[task.prependpath]$HOME/miniconda3/bin"
    displayName: 'Add conda to PATH'

  - script: conda install -y -n base conda=4.12
    displayName: 'Update conda'

#  - bash: |
#      conda create -y -n bodo_build conda-build anaconda-client conda-verify conda=4.12
#    displayName: 'Create Conda Env'
#
#  - bash: |
#      set -eo pipefail
#      source activate bodo_build
#      export BODO_VERSION=`python -m setuptools_scm`
#      cd buildscripts/bodo/bodo-conda-recipe/
#      conda build . -c bodo.ai -c conda-forge --no-test --output-folder ../../
#    displayName: 'Conda build Bodo'
#
#  - bash: |
#      set -eo pipefail
#      source activate bodo_build
#      mkdir bodo-inc
#      mkdir bodo-inc/windows-64
#      cp ./win-64/bodo*.tar.bz2 bodo-inc/windows-64/
#      conda index bodo-inc/
#    displayName: 'index bodo-inc'
