variable "github_app_id" {
  # App ID can be found in GitHub App settings
  description = "GitHub App ID for API usages."
  type        = string
}

variable "github_key_base64" {
  description = "Base64-Encoded Private Key for GitHub App."
  # Generated by running `base64 -i <path/to/private-key.pem>`
  # Private Key Downloaded Under GitHub App settings
  type = string
}

# Recommended way to pass in variables: Create a file called terraform.tfvars
# of the following format:
# 
# github_app_id = "12345"
# github_key_base64 = "base64-encoded-private-key"
# 
# Fill in with actual values
# `terraform apply` will automatically use this file
