package com.bodosql.calcite.application.utils

import com.bodosql.calcite.ir.StateVariable

/**
 * Cache of state variables generated by streaming joins.
 */
class JoinStateCache {
    private val joinMap: MutableMap<Int, Pair<StateVariable, List<Int>>> = HashMap()

    /**
     * Get the necessary code generation information for a given streaming join. This does not
     * work with non-streaming, so RuntimeJoinFilters are expected to be disabled.
     * @param joinFilterID The key mapping between join and its filter.
     * @return the state variable for the join or null if we are not streaming.
     */
    fun getStreamingJoinInfo(joinFilterID: Int): Pair<StateVariable, List<Int>> {
        return joinMap[joinFilterID]
            ?: throw IllegalStateException("Join state variable not found for key $joinFilterID")
    }

    /**
     * Set the code generation information for a streaming join.
     * @param joinFilterID The key mapping between join and its filter.
     * @param stateVariable The state variable for the join.
     */
    fun setStreamingJoinStateInfo(
        joinFilterID: Int,
        stateVariable: StateVariable,
        keyMapping: List<Int>,
    ) {
        joinMap[joinFilterID] = Pair(stateVariable, keyMapping)
    }
}
