package com.bodosql.calcite.application.utils

import com.bodosql.calcite.ir.StateVariable

/**
 * Cache of state variables generated by streaming joins.
 */
class JoinStateCache {
    private val joinMap: MutableMap<Int, StateVariable> = HashMap()

    /**
     * Get the state variable for a given streaming join. This does not
     * work with non-streaming, so RuntimeJoinFilters are expected to be disabled.
     * @param joinFilterKey The key mapping between join and its filter.
     * @return the state variable for the join or null if we are not streaming.
     */
    fun getStreamingJoinStateVariable(joinFilterKey: Int): StateVariable {
        return joinMap[joinFilterKey]
            ?: throw IllegalStateException("Join state variable not found for key $joinFilterKey")
    }

    fun setStreamingJoinStateVariable(
        joinFilterKey: Int,
        stateVariable: StateVariable,
    ) {
        joinMap[joinFilterKey] = stateVariable
    }
}
