# Copied from BodoSQL
package:
  name: bodo-iceberg-connector
  version: {{ CONNECTOR_VERSION }}

source:
  path: ../../../iceberg

build:
  noarch: python
  script_env:
    - CONNECTOR_VERSION

requirements:
  host:
    - python >=3.10,<3.13
    - setuptools >=64
    - setuptools_scm >=8
    - openjdk >=9.0,<12
    - maven

  run:
    - python >=3.10,<3.13
    - openjdk >=9.0,<12
    - py4j ==0.10.9.7
    - pyiceberg >=0.9,<0.10
    - boto3 *
    - mypy-boto3-glue *

about:
home: https://bodo.ai/
license: Apache-2.0
license_file: LICENSE
summary: Bodo Iceberg Connector
