# Copied from BodoSQL
package:
  name: bodo-iceberg-connector
  version: {{ CONNECTOR_VERSION }}

source:
  path: ../../../iceberg

build:
  noarch: python
  script_env:
    - CONNECTOR_VERSION

requirements:
  host:
    - python >=3.10,<3.13
    - setuptools >=64
    - setuptools_scm >=8
    - openjdk >=9.0,<12
    - maven

  run:
    - python >=3.10,<3.13
    - openjdk >=9.0,<12
    - py4j ==0.10.9.7

about:
home: https://bodo.ai/
license: Proprietary
license_file: LICENSE.md
summary: Bodo Iceberg Connector
