# Copied from BodoSQL
package:
  name: bodo-iceberg-connector
  version: {{ CONNECTOR_VERSION }}

source:
  path: ../../../iceberg

build:
  noarch: python

requirements:
  host:
    - python >=3.8,<3.11
    - setuptools
    - openjdk >=9.0
    - maven
    - ninja
    - bodo >=2022.05

  run:
    - openjdk >=9.0
    - bodo >=2022.05
    - jpype1
    - python >=3.8,<3.11

build:
  script_env:
    - CONNECTOR_VERSION


about:
home: https://bodo.ai/
license: Proprietary
license_file: LICENSE.md
summary: Bodo Iceberg Connector
