# Copied from BodoSQL
package:
  name: bodo-iceberg-connector
  version: {{ CONNECTOR_VERSION }}

source:
  path: ../../../iceberg

build:
  noarch: python
  script_env:
    - CONNECTOR_VERSION

requirements:
  host:
    - python >=3.8,<3.11
    - setuptools
    - openjdk >=9.0
    - maven
    - ninja

  run:
    - python >=3.8,<3.11
    - openjdk >=9.0
    - py4j ==0.10.9.5

about:
home: https://bodo.ai/
license: Proprietary
license_file: LICENSE.md
summary: Bodo Iceberg Connector
