---

- name: JLAB-EXECUTE-TIME | Create user-settings directory
  file:
    path: /home/{{ CLUSTER_USER }}/.jupyter/lab/user-settings/@jupyterlab/notebook-extension/
    state: directory
    owner: "{{ CLUSTER_USER }}"
    group: "{{ CLUSTER_USER }}"
    mode: "0755"
  tags:
    - jupyter

- name: JLAB-EXECUTE-TIME | Upload user-settings json file to enable cell recordTiming
  copy:
    src: jlab_execute_time_user_settings.json
    dest: /home/{{ CLUSTER_USER }}/.jupyter/lab/user-settings/@jupyterlab/notebook-extension/tracker.jupyterlab-settings
    owner: "{{ CLUSTER_USER }}"
    group: "{{ CLUSTER_USER }}"
    mode: "0644"
  tags:
    - jupyter
