---
- name: JUPYTER | Check if conda is installed
  stat:
    path: /opt/conda/bin/conda
  register: conda
  tags:
    - jupyter

- name: JUPYTER | Upload environemnt file to /tmp/jupyter_env.yaml
  template:
    dest: /tmp/jupyter_env.yaml
    src: ../files/jupyter_env.yaml
    owner: "{{ CLUSTER_USER }}"
    group: "{{ CLUSTER_USER }}"
    mode: '0644'
  tags:
    - jupyter

- name: JUPYTER | Install all dependencies from the environment file
  command:
    cmd: "/opt/conda/bin/mamba env update --name base --file /tmp/jupyter_env.yaml"
  tags:
    - jupyter

- name: JUPYTER | Upload systemd jupyter service
  template:
    dest: /etc/systemd/system/jupyter.service
    src: jupyter.service.j2
    owner: root
    group: root
    mode: "0644"
  tags:
    - jupyter

- name: JUPYTER | Create jupyter directory
  file:
    path: /home/{{ CLUSTER_USER }}/.jupyter/
    state: directory
    owner: "{{ CLUSTER_USER }}"
    group: "{{ CLUSTER_USER }}"
    mode: "0755"
  tags:
    - jupyter

- name: JUPYTER | Upload jupyter config file
  copy:
    src: jupyter_notebook_config.py
    dest: /home/{{ CLUSTER_USER }}/.jupyter/jupyter_notebook_config.py
    owner: "{{ CLUSTER_USER }}"
    group: "{{ CLUSTER_USER }}"
    mode: "0644"
  tags:
    - jupyter

- name: JUPYTER | Reload jupyter service
  systemd:
    name: jupyter.service
    daemon_reload: yes
  tags:
    - jupyter

- name: JUPYTER | Add PS1 to bashrc to see user/host/dir in command prompt.
  blockinfile:
    path: "/home/{{ CLUSTER_USER }}/.bashrc"
    insertbefore: '.*'
    marker: "#<!-- {mark} Adding PS1 to see user/host/dir in command prompt -->"
    block: |
      export PS1="\[\033[0;32m\]\u@\h: \[\033[36m\]\W\[\033[0m\] \$ "
  tags:
    - jupyter
