package:
  name: bodo
  version: {{ BODO_VERSION }}

source:
   path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  script_env:
  - CHECK_LICENSE_EXPIRED
  - CHECK_LICENSE_CORE_COUNT
  - CHECK_LICENSE_PLATFORM
  rpaths:
    - lib
    - {{ PREFIX }}/lib
    - {{ SP_DIR }}/pyarrow

build_platform:
  osx_arm64: osx_64
test_on_native_only: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3.0                           # [build_platform != target_platform]
    - numpy  >=1.18,<1.24                    # [build_platform != target_platform]
    - arrow-cpp =11.0.0                      # [build_platform != target_platform]
    - pyarrow =11.0.0                        # [build_platform != target_platform]
    - numba 0.56.4

  host:
    - python
    # setuptools>=65 removes the msvc compilers that
    # distutils/extension uses.
    # TODO[BE-3467]: remove distutils
    - setuptools <63
    # Compatable with Numba requirements.
    # Resolves build issues on nightly
    - numpy >=1.18,<1.24
    - cython <3.0
    - pandas >=1.3.*,<1.5
    - fsspec >=2021.09
    - arrow-cpp =11.0.0
    - pyarrow =11.0.0
    - boost-cpp =1.82
    - libcurl
    # We suport both 1.10 and 1.12. Since
    # M1 only support 1.12 with Python 3.10.
    - hdf5 >=1.10.*,<1.13.0a0=*mpi_mpich_* # [not win]
    - h5py
    - mpich >=3.3,<4.0.0a0=h* # [not win]
    - msmpi # [win]
    - mpi4py
    - vc # [win]
    - vs2015_runtime # [win]
    - vs2015_win-64 # [win]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas >=1.3.*,<1.5
    - fsspec >=2021.09
    - pyarrow =11.0.0
    - libcurl
    - numba =0.56.4
    - mpich >=3.3,<4.0.0a0=h* # [not win]
    - msmpi # [win]
    - mpi4py
    - vs2015_runtime # [win]
    - vs2015_win-64 # [win]

  # run constrained will not install these packages when building,
  # but will restrict them if they are present in the conda env.
  # currently matplotlib is an optional dependency, and we only
  # support up to 3.5.1
  run_constrained:
    - matplotlib <= 3.5.1

  run_constrained:
    - numpy >=1.18,<1.24
test:
  imports:
    - bodo
  source_files:
    - examples/pi.py


about:
  home: https://bodo.ai
  license: Proprietary
  license_file: LICENSE.md
  summary: Python Supercomputing Analytics Platform
