package:
  name: bodo
  version: {{ BODO_VERSION }}

source:
   path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  script_env:
  - CHECK_LICENSE_EXPIRED
  - CHECK_LICENSE_CORE_COUNT
  - CHECK_LICENSE_PLATFORM
  rpaths:
    - lib
    - {{ PREFIX }}/lib
    - {{ SP_DIR }}/pyarrow

build_platform:
  osx_arm64: osx_64
test_on_native_only: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - cython <3.0                           # [build_platform != target_platform]
    - numpy >=1.23                          # [build_platform != target_platform]
    - libarrow =14.0.2                      # [build_platform != target_platform]
    - pyarrow =14.0.2                       # [build_platform != target_platform]
    - numba 0.58.1

  host:
    - python
    - setuptools
    # Compatible with Numba requirements.
    # Resolves build issues on nightly
    - numpy >=1.23,<1.27
    - cython <3.0
    - pandas >=2,<2.1
    - fsspec >=2021.09
    - libarrow =14.0.2
    - pyarrow =14.0.2
    - boost-cpp =1.84
    - fmt =10.1
    - libcurl <=8.5
    - hdf5 >=1.14.3,<1.14.4.0a0=*mpi_mpich_* # [not win]
    - h5py
    - mpich *=h* # [not win]
    - msmpi # [win]
    - mpi4py
    - vc # [win]
    - vs2015_runtime # [win]
    - vs2015_win-64 # [win]
    - fftw >=3.3.10,<3.4.0a0=*mpi_mpich_*

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas >=2,<2.1
    - fsspec >=2021.09
    - pyarrow =14.0.2
    - numba =0.58.1
    - mpich *=h* # [not win]
    - msmpi # [win]
    - mpi4py
    - vs2015_runtime # [win]
    - vs2015_win-64 # [win]
    - fftw >=3.3.10,<3.4.0a0=*mpi_mpich_*

  # run constrained will not install these packages when building,
  # but will restrict them if they are present in the conda env.
  # currently matplotlib is an optional dependency, and we only
  # support up to 3.5.1
  run_constrained:
    - matplotlib <= 3.5.1
  run_constrained:
    - numpy >=1.23,<1.27
  run_constrained:
    - scikit-learn =1.1.*
  run_constrained:
    - s3fs >=2022.1.0


test:
  imports:
    - bodo
  source_files:
    - examples/pi.py


about:
  home: https://bodo.ai
  license: Proprietary
  license_file: LICENSE.md
  summary: Python Supercomputing Analytics Platform
