CONDA_BUILD_SYSROOT:
  - /opt/MacOSX11.0.sdk        # [osx]

MACOSX_DEPLOYMENT_TARGET:
  - 11.0

python:
  - 3.12

numpy:
  - 1.23

target_platform:
  - osx-arm64

SDKROOT:
  - /opt

c_compiler_version:
  - 18
cxx_compiler_version:
  - 18
