# Copied from BodoSQL
parameters:
    name: ''
    pythonVersion: ''

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 240
  pool: ScalingVMSet

  steps:
  # Install Micromamba and Create Environment. Reference:
  # https://mamba.readthedocs.io/en/latest/installation.html#micromamba
  - script: |
      set -exo pipefail
      curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
      eval "$(./bin/micromamba shell hook -s posix)"

      micromamba create -y -n iceberg_build python=$PYTHON_VERSION boa anaconda-client conda-verify setuptools_scm -c conda-forge
    env:
      PYTHON_VERSION: ${{ parameters.pythonVersion }}
    displayName: 'Create Micromamba Env'

  - task: DownloadSecureFile@1
    name: secret_file
    displayName: 'Download Secrets File'
    inputs:
      secureFile: 'publish_binary_secrets'

  - script: |
      set -eo pipefail
      sudo chmod a+r $(secret_file.secureFilePath)
      sudo cp $(secret_file.secureFilePath) $HOME/secret_file

      artifactory_channel=`./buildscripts/iceberg/get_channel.sh`
      echo "artifactory_channel: $artifactory_channel"
      buildscripts/iceberg/publish_binary.sh $artifactory_channel
    env:
      TARGET_NAME: ${{ parameters.name }}
    displayName: 'Conda Build and Publish Iceberg Binary to Artifactory'
