parameters:
- name: name
  type: string
  default: ''
- name: CONDA_ENV
  type: string
  default: ''
- name: matrix
  type: object
  default: []
- name: CACHE_TEST
  type: boolean
  default: false
- name: BODO_STREAMING_ENABLED
  type: number
  default: 0

jobs:
- job: ${{ parameters.name }}
  variables:
    - group: SnowflakeCredentials
  timeoutInMinutes: 360
  pool: ScalingVMSet
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
  # TODO: Use Micromamba when it supports remote_max_retries
  - script: |
      set -exo pipefail
      curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
      bash Mambaforge-$(uname)-$(uname -m).sh -b
    displayName: 'Install Mambaforge'

  - bash: echo "##vso[task.prependpath]$HOME/mambaforge/bin"
    displayName: Add Mamba to PATH

  - script: |
      conda config --set remote_max_retries 5
      conda config --set remote_backoff_factor 60
      # Ensure that conda/mamba install/update/remove commands
      # do not try to mutate the environment beyond what's required.
      conda config --add aggressive_update_packages nodefaults
    displayName: 'Set conda config'

  - script: |
      source activate base
      mamba install -y pip
      pip install pipx
      pipx run conda-lock install -n ${{ parameters.CONDA_ENV }} $(System.DefaultWorkingDirectory)/buildscripts/envs/conda-lock.yml
    displayName: 'Create Mamba Env'

  - task: DownloadSecureFile@1
    name: secret_file
    inputs:
      secureFile: 'publish_binary_secrets'
    displayName: 'Download Secrets File'

  - script: |
      set -eo pipefail
      source activate ${{ parameters.CONDA_ENV }}
      set -x

      sudo chmod a+r $(secret_file.secureFilePath)
      sudo cp $(secret_file.secureFilePath) $HOME/secret_file

      cd $(System.DefaultWorkingDirectory)
      ./buildscripts/bodosql/azure/artifactory_install.sh "false"
    env:
      CONDA_ENV:  ${{ parameters.CONDA_ENV }}
    displayName: 'Install Bodo, BodoSQL, and Iceberg from Artifactory'

  - script: |
      set -exo pipefail
      mkdir -p $HOME/bodo-inc
      cd $HOME/bodo-inc
      mkdir bodosql

      unamestr=`uname`
      if [[ "$unamestr" == 'Linux' ]]; then
        cp -avr $(System.DefaultWorkingDirectory)/BodoSQL/bodosql/tests bodosql/
      else
        cp -r $(System.DefaultWorkingDirectory)/BodoSQL/bodosql/tests bodosql
      fi
    displayName: 'Copy Tests and Test Data'

  - task: DownloadSecureFile@1
    name: testLicense
    inputs:
      secureFile: 'bodo.lic'
    displayName: 'Download Test License'

  - script: |
      set -eo pipefail
      source activate ${{ parameters.CONDA_ENV }}
      set -x

      sudo chmod a+r $(testLicense.secureFilePath)
      sudo cp $(testLicense.secureFilePath) $HOME/bodo-inc

      cd $HOME/bodo-inc
      cp `python -c "import bodosql; print(bodosql.__file__[:-11])"`pytest.ini .
      # For caching tests we need to update the location of the decryption file.
      # We set the absolute path as an environment variable.
      export BODO_TRACING_DECRYPTION_FILE_PATH=`echo "$(System.DefaultWorkingDirectory)/obfuscation/decompress_traces.py"`
      if [[ "${{ parameters.CACHE_TEST }}" == "True" ]]; then
        python -u -m bodosql.runtests_caching "${{ parameters.name }}" "$(NP)" bodosql/tests/caching_tests/
      else
        python -u -m bodosql.runtests "${{ parameters.name }}" "$(NP)" -s -v -p no:faulthandler -m "$(PYTEST_MARKER)" bodosql/tests/
      fi
    env:
      SF_USERNAME: $(SNOWFLAKE_USER)
      SF_PASSWORD: $(SNOWFLAKE_PASSWORD)
      BODO_STREAMING_ENABLED: ${{ parameters.BODO_STREAMING_ENABLED }}
    displayName: 'Test BodoSQL'
