parameters:
    name: ''
    vmImage: ''
    CONDA_ENV: ''
    PYTHON_VERSION: ''

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 240
  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
    displayName: 'Use Python 3.9'

  - script: |
      set -exo pipefail
      wget https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh -O mambaforge.sh
      chmod +x mambaforge.sh
      bash mambaforge.sh -b
      export PATH=$HOME/mambaforge/bin:$PATH
      mamba create -n $CONDA_ENV -q -y -c conda-forge python=$PYTHON_VERSION
    env:
      CONDA_ENV:  ${{ parameters.CONDA_ENV }}
      PYTHON_VERSION: ${{ parameters.PYTHON_VERSION }}
    displayName: 'Setup Conda Installation + Dependencies'

  - task: DownloadSecureFile@1
    name: secret_file
    inputs:
      secureFile: 'publish_binary_secrets'
    displayName: 'Download Secrets File'

  - script: |
      set -eo pipefail
      sudo chmod a+r $(secret_file.secureFilePath)
      sudo cp $(secret_file.secureFilePath) $HOME/secret_file
      artifactory_channel=`./buildscripts/bodosql/azure/get_channel.sh`
      echo "artifactory_channel: $artifactory_channel"
      ./buildscripts/bodosql/azure/publish_binary.sh $artifactory_channel
    env:
      CONDA_ENV:  ${{ parameters.CONDA_ENV }}
      TARGET_NAME: ${{ parameters.name }}
    displayName: 'Conda Build and Publish BodoSQL Binary to Artifactory'
