parameters:
  name: ''
  vmImage: ''
  CONDA_ENV: ''
  BODO_CHANNEL_NAME: ''
  PYTHON_VERSION: ''

jobs:
- job: ${{ parameters.name }}
  variables:
    - group: SnowflakeCredentials
  timeoutInMinutes: 360
  pool: ScalingVMSet

  steps:

  - script: |
      set -eo pipefail
      cd $(System.DefaultWorkingDirectory)/BodoSQL/calcite_sql/
      sudo apt-get install maven -y
      sudo mvn -B -U test
    displayName: 'Run maven tests for BodoSQL'

