on:
  workflow_call:
    inputs:
      test-type:
        type: string
        # options:
        #   - spawn
        #   - compiler
        #   - cache
        #   - df_lib
        #   - sql
        #   - sql_spawn
        #   - sql_cache
        description: The kind of tests to run e.g. spawn tests
        required: true
      runner-id:
        type: string
        # options:
        #   - ubuntu-latest
        #   - windows-latest
        #   - ubuntu-24.04-arm
        description: The kind of runner to use
        required: true
      num-workers:
        type: string
        description: 'Number of workers to test'
        required: true
      pytest-marker:
        description: 'Pytest marker expression to select tests to run'
        required: true
        type: string
      extra-markers:
        description: 'Additional pytest markers to select tests to run e.g. spawn_mode'
        required: false
        default: ""
        type: string
      partition:
        type: string
        description: 'Partition to run tests on (e.g. bodo_1of22)'
        required: false
        default: ""

jobs:
  run-tests:
    permissions:
      id-token: write
      contents: read
    runs-on: ${{ inputs.runner-id }}
    steps:
      - name: Create Test Marker
        id: set-marker
        run: |
          MARKER="${{ inputs.pytest-marker }}"

          append_marker() {
              local expr="$1"
              [[ -z "$expr" ]] && return

              if [[ -n "$MARKER" ]]; then
                  MARKER="$MARKER and $expr"
              else
                  MARKER="$expr"
              fi
          }

          append_marker "${{ inputs.partition }}"
          append_marker "${{ inputs.extra-markers }}"

          echo "PYTEST_MARKER=$MARKER" >> "$GITHUB_ENV"
      - uses: actions/checkout@v5
      - name: Build from Source
        uses: ./.github/actions/build-source
        with:
          build-iceberg: true
          build-bodosql: ${{ startsWith(inputs.test-type, 'sql') }}
          environment: "default"
      - name: Clean Maven and Spark Ivy Cache
        run: |
          rm -rf "$HOME"/.ivy2/cache "$HOME"/.ivy2/jars "$HOME"/.m2/repository
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::427443013497:role/BodoEngineNightlyRole
          role-session-name: BodoEnginePrCiSession
          role-skip-session-tagging: true
          role-duration-seconds: 14400 # Max duration: 4 hours
      - name: Install Polaris
        run: |
            pip install --no-deps 'git+https://github.com/apache/polaris.git@release/1.0.x#subdirectory=client/python'
      - name: Run Tests
        run: |
          # For caching tests we need to update the location of the decryption file.
          # We set the absolute path as an environment variable.
          export BODO_TRACING_DECRYPTION_FILE_PATH=\
              "$WORKING_DIR/buildscripts/decompress_traces.py"

          # Ignore streaming/caching/metadata tests in Dataframes/Spawn mode
          # to avoid importing JIT during test collection.
          PYTEST_IGNORE="--ignore bodo/tests/test_streaming \
          --ignore bodo/tests/caching_tests"

          if [[ "$TEST_TYPE" == sql* ]]; then
              cd "$WORKING_DIR/BodoSQL"
          fi

          if [[ "$TEST_TYPE" == "cache" ]]; then
              python -m bodo.runtests_caching \
                  "$TEST_NAME" \
                  "$NP" \
                  bodo/tests/caching_tests

          elif [[ "$TEST_TYPE" == "spawn" ]]; then
              # Disabling the DataFrame library for spawn tests since some of the tests
              # create Pandas manager states for testing that are not fully functional.
              export BODO_ENABLE_DATAFRAME_LIBRARY=0
              export BODO_TEST_SPAWN_MODE=1
              export BODO_NUM_WORKERS="$NP"

              pytest \
                  -s -v -Wignore \
                  -m "$PYTEST_MARKER" \
                  $PYTEST_IGNORE \
                  bodo/tests \
                  --junitxml=pytest-report-spawn-mode.xml \
                  --test-run-title="$TEST_NAME"

          elif [[ "$TEST_TYPE" == "df_lib" ]]; then
              export BODO_ENABLE_TEST_DATAFRAME_LIBRARY=1
              export BODO_NUM_WORKERS="$NP"

              pytest \
                  -s -v -Wignore \
                  -m "$PYTEST_MARKER and not jit_dependency" \
                  $PYTEST_IGNORE \
                  bodo/tests \
                  --junitxml=pytest-report-df-library.xml \
                  --test-run-title="$TEST_NAME"

              # Run tests with JIT dependency separately to avoid JIT imports
              # impacting other tests.
              pytest \
                  -s -v -Wignore \
                  -m "$PYTEST_MARKER and jit_dependency" \
                  $PYTEST_IGNORE \
                  bodo/tests \
                  --junitxml=pytest-report-df-library-jit-dependency.xml \
                  --test-run-title="$TEST_NAME - JIT"

          elif [[ "$TEST_TYPE" == "compiler" ]]; then
              # Some tests assume a batch size of 4096 for testing specific behavior.
              export BODO_STREAMING_BATCH_SIZE=4096

              python -m bodo.runtests \
                  "$TEST_NAME" \
                  "$NP" \
                  --pyargs bodo \
                  -s -v \
                  -m "$PYTEST_MARKER"

          elif [[ "$TEST_TYPE" == "sql_cache" ]]; then
              python -u -m bodosql.runtests_caching \
                  "$TEST_NAME" \
                  "$NP" \
                  bodosql/tests/caching_tests/

          elif [[ "$TEST_TYPE" == "sql_spawn" ]]; then
              export BODO_TEST_SPAWN_MODE=1
              export BODO_NUM_WORKERS="$NP"

              pytest \
                  -s -v \
                  -p no:faulthandler \
                  -Wignore \
                  -m "$PYTEST_MARKER" \
                  bodosql/tests \
                  --junitxml=pytest-report-sql-spawn-mode.xml \
                  --test-run-title="$TEST_NAME"

          elif [[ "$TEST_TYPE" == "sql" ]]; then
              python -u -m bodosql.runtests \
                  "$TEST_NAME" \
                  "$NP" \
                  -s -v \
                  -p no:faulthandler \
                  -m "$PYTEST_MARKER" \
                  bodosql/tests/

          else
              echo "Invalid TEST_TYPE: $TEST_TYPE"
              exit 1
          fi
        env:
          WORKING_DIR: ${{ github.workspace }}
          TEST_NAME: "${{ github.run_id }}-${{ inputs.test-type }}"
          TEST_TYPE: ${{ inputs.test-type }}
          NP: ${{ inputs.num-workers }}
          BODO_NUM_WORKERS: ${{ inputs.num-workers }}
          BODO_SPAWN_MODE: "0"
          BODO_BUFFER_POOL_REMOTE_MODE: "1"
          BODO_BUFFER_POOL_DEBUG_MODE: "1"
          BODO_SF_WRITE_DEBUG: "1"
          # Testing credentials
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_AZURE_USER: ${{ secrets.SF_AZURE_USER }}
          SF_AZURE_PASSWORD: ${{ secrets.SF_AZURE_PASSWORD }}
          SF_AZURE_ACCOUNT: ${{ secrets.SF_AZURE_ACCOUNT }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          BODO_TEST_SQL_DB_CREDENTIAL: ${{ secrets.BODO_TEST_SQL_DB_CREDENTIAL }}
          BODO_TEST_ORACLE_DB_CREDENTIAL: ${{ secrets.BODO_TEST_ORACLE_DB_CREDENTIAL }}
          AZURE_CLIENT_ID:  ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: "ac373ae0-dc77-4cbb-bbb7-deddcf6133b3"
