name: BodoSQL Java Tests
on:
  # Pull Request that Modifies BodoSQL Java
  pull_request:
    paths:
      - 'BodoSQL/calcite_sql/**'

# Limit CI to cancel previous runs in the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

jobs:
  get-msg:
    name: Get Commit Message
    runs-on: ubuntu-latest
    outputs:
      commitMsg: ${{ steps.get_msg.outputs.commitMsg }}
    steps:
      # Fetch the branch for the history only
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          sparse-checkout: .
      - name: Get Commit Message
        id: get_msg
        run: |
          set -xe pipefail
          echo "commitMsg=$(git log -1 --pretty=format:'%s')" >> $GITHUB_OUTPUT

  run-java:
    needs: [get-msg]
    name: Run BodoSQL Java Tests
    runs-on: [self-hosted, large]
    # https://docs.github.com/en/actions/learn-github-actions/expressions#contains
    # contains is case-insensitive
    if: contains(needs.get-msg.outputs.commitMsg, '[run ci]')
    steps:
      - uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          cache-dependency-path: 'BodoSQL/calcite_sql/bodosql-calcite-application/pom.xml'
      - name: Install Maven
        run: sudo yum install maven -y
      - name: Run Maven Tests
        run: |
          which mvn
          cd BodoSQL/calcite_sql/
          mvn -B -U test
        
      # Publishing Test Results
      # Always run both even if tests fail
      - name: Publish Test Result Failures
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: 'BodoSQL/calcite_sql/bodosql-calcite-application/target/surefire-reports/TEST-*.xml'        
      - name: Publish Test Results in Comment
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success() || failure()
        with:
          files: 'BodoSQL/calcite_sql/bodosql-calcite-application/target/surefire-reports/TEST-*.xml'
