name: Bodo & BodoSQL Nightly CI

on:
  workflow_dispatch:
    inputs:
      pytest-marker:
        description: 'Additional pytest marker to select tests to run'
        required: false
        default: ""
        type: string
      weekly:
        description: 'Whether to include tests marked "weekly"'
        required: false
        default: false
        type: boolean
      runner-id:
        description: 'Runner ID to select tests to run'
        required: false
        default: ubuntu-latest
        type: string
  workflow_call:
    inputs:
      pytest-marker:
        description: 'Additional pytest marker to select tests to run'
        required: false
        default: ""
        type: string
      weekly:
        description: 'Whether to include tests marked "weekly"'
        required: false
        default: false
        type: boolean
      runner-id:
        description: 'Runner ID to select tests to run'
        required: false
        default: ubuntu-latest
        type: string
  schedule:
    - cron: '0 2 * * 1-5'    # 9:00 PM EST Sunday-Friday

jobs:
  create-test-marker:
    runs-on: ubuntu-latest
    outputs:
      pytest-marker: ${{ steps.set-marker.outputs.pytest-marker }}
    steps:
      - id: set-marker
        name: Create Test Marker
        run: |
          MARKER="${{ inputs.pytest-marker }}"

          # Add "not weekly" unless running weekly tests
          if [[ "${{ inputs.weekly }}" != "true" ]]; then
            if [[ -n "$MARKER" ]]; then
              MARKER="$MARKER and not weekly"
            else
              MARKER="not weekly"
            fi
          fi

          echo "pytest-marker=$MARKER" >> "$GITHUB_OUTPUT"
        shell: bash

  bodo-compiler-1p:
    needs: create-test-marker
    strategy:
      matrix:
        batch: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
      fail-fast: false
    uses: ./.github/workflows/_test_nightly_python_source.yml
    with:
      pytest-marker: ${{ needs.create-test-marker.outputs.pytest-marker }}
      partition: bodo_${{ matrix.batch }}of22
      test-type: compiler
      runner-id: ${{ inputs.runner-id || 'ubuntu-latest' }}
      num-workers: 1
    secrets: inherit

  bodo-compiler-2p:
    needs: create-test-marker
    strategy:
      matrix:
        batch: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
      fail-fast: false
    uses: ./.github/workflows/_test_nightly_python_source.yml
    with:
      pytest-marker: ${{ needs.create-test-marker.outputs.pytest-marker }}
      test-type: compiler
      partition: bodo_${{ matrix.batch }}of30
      runner-id: ${{ inputs.runner-id || 'ubuntu-latest' }}
      num-workers: 2
    secrets: inherit

  bodo-cache:
    needs: create-test-marker
    uses: ./.github/workflows/_test_nightly_python_source.yml
    with:
      pytest-marker: ${{ needs.create-test-marker.outputs.pytest-marker }}
      test-type: cache
      runner-id: ${{ inputs.runner-id || 'ubuntu-latest' }}
      num-workers: 2
    secrets: inherit

  bodo-spawn-1p:
    needs: create-test-marker
    uses: ./.github/workflows/_test_nightly_python_source.yml
    with:
      pytest-marker: ${{ needs.create-test-marker.outputs.pytest-marker }}
      extra-markers: spawn_mode
      test-type: spawn
      runner-id: ${{ inputs.runner-id || 'ubuntu-latest' }}
      num-workers: 1
    secrets: inherit

  bodo-spawn-2p:
    needs: create-test-marker
    uses: ./.github/workflows/_test_nightly_python_source.yml
    with:
      pytest-marker: ${{ needs.create-test-marker.outputs.pytest-marker }}
      extra-markers: spawn_mode
      test-type: spawn
      runner-id: ${{ inputs.runner-id || 'ubuntu-latest' }}
      num-workers: 2
    secrets: inherit

  bodo-df-lib-1p:
    needs: create-test-marker
    uses: ./.github/workflows/_test_nightly_python_source.yml
    with:
      pytest-marker: ${{ needs.create-test-marker.outputs.pytest-marker }}
      extra-markers: df_lib
      test-type: df_lib
      runner-id: ${{ inputs.runner-id || 'ubuntu-latest' }}
      num-workers: 1
    secrets: inherit

  bodo-df-lib-2p:
    needs: create-test-marker
    uses: ./.github/workflows/_test_nightly_python_source.yml
    with:
      pytest-marker: ${{ needs.create-test-marker.outputs.pytest-marker }}
      extra-markers: df_lib
      test-type: df_lib
      runner-id: ${{ inputs.runner-id || 'ubuntu-latest' }}
      num-workers: 2
    secrets: inherit

  bodosql-1p:
    needs: create-test-marker
    strategy:
      matrix:
        batch: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
      fail-fast: false
    uses: ./.github/workflows/_test_nightly_python_source.yml
    with:
      pytest-marker: ${{ needs.create-test-marker.outputs.pytest-marker }}
      partition: bodosql_${{ matrix.batch }}of12
      test-type: sql
      runner-id: ${{ inputs.runner-id || 'ubuntu-latest' }}
      num-workers: 1
    secrets: inherit

  bodosql-2p:
    needs: create-test-marker
    strategy:
      matrix:
        batch: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
      fail-fast: false
    uses: ./.github/workflows/_test_nightly_python_source.yml
    with:
      pytest-marker: ${{ needs.create-test-marker.outputs.pytest-marker }}
      partition: bodosql_${{ matrix.batch }}of22
      test-type: sql
      runner-id: ${{ inputs.runner-id || 'ubuntu-latest' }}
      num-workers: 2
    secrets: inherit

  bodosql-cache:
    needs: create-test-marker
    uses: ./.github/workflows/_test_nightly_python_source.yml
    with:
      pytest-marker: ${{ needs.create-test-marker.outputs.pytest-marker }}
      test-type: sql_cache
      runner-id: ${{ inputs.runner-id || 'ubuntu-latest' }}
      num-workers: 2
    secrets: inherit

  bodosql-spawn-1p:
    needs: create-test-marker
    uses: ./.github/workflows/_test_nightly_python_source.yml
    with:
      pytest-marker: ${{ needs.create-test-marker.outputs.pytest-marker }}
      extra-markers: spawn_mode
      test-type: sql_spawn
      runner-id: ${{ inputs.runner-id || 'ubuntu-latest' }}
      num-workers: 1
    secrets: inherit

  bodosql-spawn-2p:
    needs: create-test-marker
    uses: ./.github/workflows/_test_nightly_python_source.yml
    with:
      pytest-marker: ${{ needs.create-test-marker.outputs.pytest-marker }}
      extra-markers: spawn_mode
      test-type: sql_spawn
      runner-id: ${{ inputs.runner-id || 'ubuntu-latest' }}
      num-workers: 2
    secrets: inherit

  merge-junit:
    needs: [
      bodo-compiler-1p,
      bodo-compiler-2p,
      bodo-cache,
      bodo-spawn-1p,
      bodo-spawn-2p,
      bodo-df-lib-1p,
      bodo-df-lib-2p,
      bodosql-1p,
      bodosql-2p,
      bodosql-cache,
      bodosql-spawn-1p,
      bodosql-spawn-2p
    ]
    if: always()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - run: |
          pip install junitparser junit2html

      - name: Download Bodo reports
        uses: actions/download-artifact@v4
        with:
          pattern: junit-reports-compiler-*
          path: bodo-reports
          merge-multiple: true

      - name: Download BodoSQL reports
        uses: actions/download-artifact@v4
        with:
          pattern: junit-reports-sql-*
          path: bodosql-reports
          merge-multiple: true

      - name: Merge XML
        run: |
          junitparser merge bodo-reports/*.xml bodo.xml
          junit2html bodo.xml bodo.html

          junitparser merge bodosql-reports/*.xml bodosql.xml
          junit2html bodosql.xml bodosql.html

      - name: Upload merged reports
        uses: actions/upload-artifact@v4
        with:
          name: merged-junit-reports
          path: |
            bodo.xml
            bodo.html
            bodosql.xml
            bodosql.html
