name: Bodo Nightly CI

on:
  workflow_dispatch:
    inputs:
      pytest_marker:
        description: 'Additional pytest marker to select tests to run'
        required: false
        default: ""
        type: string
  schedule:
    - cron: '00 21 * * 0,1,2,3,4'    # 9:00PM EST Sunday-Friday
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

jobs:
  bodo-compiler-1p:
    strategy:
      matrix:
        batch: [1]
      fail-fast: false
    uses: ./.github/workflows/_test_nightly_python_source.yml
    with:
      pytest_marker: ${{ inputs.pytest_marker }}
      test-type: compiler
      runner-id: ubuntu-latest
      batch: ${{ matrix.batch }}
