name: PR CI Auto
on:
  pull_request:

# Limit CI to cancel previous runs in the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

jobs:

  python-code-test:
    name: Python Code Test
    runs-on: ubuntu-latest
    steps:
      - name: Check format Python
        uses: astral-sh/ruff-action@v2
        with:
          args: "format --check"
