name: PR CI Auto
on:
  pull_request:

# Limit CI to cancel previous runs in the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

jobs:

  python-code-test:
    name: Python Code Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check format Python
        uses: astral-sh/ruff-action@v2
        with:
          version: "0.6.7"
          args: "format --check"

  clang-code-test:
    name: Clang Code Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.14.0
        with:
          clang-format-version: '19'
          exclude-regex: (bodo\/libs\/vendored\/.*|bodo\/libs\/HashLibs\/.*)$

  java-code-test:
    name: Java/Kotlin Code Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: axel-op/googlejavaformat-action@v3
        name: Google Java Format
        with:
          args: "--dry-run"
