name: Publish images to production

on:
  workflow_dispatch:
    inputs:
      buildRunId:
        description: The run id of the build workflow
        required: true

jobs:
  share-images-with-prod-platform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install requests

      - name: Download Image Entries Request JSON
        uses: actions/download-artifact@v4
        with:
          name: img-entries-request-json
          path: bodo-platform-image/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.inputs.buildRunId }}

      - name: Share Images with Prod Platform
        id: share
        env:
          AUTH_SERVICE_URL: "https://bodo.us.frontegg.com"
          BOT_PLATFORM_USERNAME: ${{ secrets.BOT_PROD_PLATFORM_USERNAME }}
          BOT_PLATFORM_PASSWORD: ${{ secrets.BOT_PROD_PLATFORM_PASSWORD }}
          BACKEND_SERVICE_URL: "https://api.bodo.ai"
          ORGANIZATION_UUID: ${{ secrets.PROD_ORGANIZATION_UUID }}
        working-directory: bodo-platform-image
        run: |
          sleep 120
          python manage_images.py
