name: Bodo Weekly CI

on:
  workflow_dispatch:
    inputs:
      pytest-marker:
        description: 'Additional pytest marker to select tests to run'
        required: false
        default: ""
        type: string
  schedule:
    - cron: '00 21 * * 5'    # 9:00PM EST every Friday
  pull_request:


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  weekly-linux-64-ci:
    uses: ./.github/workflows/nightly.yml
    with:
      pytest-marker: ${{ inputs.pytest-marker }}
      weekly: true
    secrets: inherit

  weekly-linux-arm-ci:
    uses: ./.github/workflows/nightly.yml
    with:
      pytest-marker: ${{ inputs.pytest-marker }}
      weekly: false
      runner-id: ubuntu-24.04-arm
    secrets: inherit

# TODO: Test Windows
