name: Run PR CI on Windows
on:
  pull_request:
  workflow_dispatch:

# Limit CI to cancel previous runs in the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

jobs:

  # 3) Pre-Build Bodo to save build artifacts to sccache
  compile-bodo:
    name: Pre-Build Bodo for Cache
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Build from Source
        uses: ./.github/actions/build-source
        with:
          build-all: false

  # 4) Actually run tests
  pr-ci:
    needs: [compile-bodo]
    name: Test
    strategy:
      matrix:
        batch: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
      # Don't cancel other jobs if one fails
      fail-fast: false
    uses: ./.github/workflows/_test_python_source.yml
    with:
      batch: ${{ matrix.batch }}
      total-batches: 12
      pytest-marker: "not slow and not weekly or smoke"
      collect-coverage: false
      os: 'windows-latest'
    secrets: inherit

  # TODO: enabke spawn mode tests
  # spawn-ci:
  #   needs: [compile-bodo]
  #   name: Test Spawn
  #   uses: ./.github/workflows/_test_python_source.yml
  #   with:
  #     batch: 1
  #     total-batches: 1
  #     pytest-marker: "spawn_mode"
  #     collect-coverage: false
  #     os: 'windows-latest'
  #   secrets: inherit
